Block counter in editor
ScratchAddons/ScratchAddons pull request #1121
Opened 2020-12-29 04:53 UTC by TheColaber

**Resolves**

Resolves #1115

**Changes**

Add a setting for the project-info addon to enable a live block count in the editor.

**Tests**

This is tested and everything works and is way faster for that matter... I'm just dealing with this order...
![image](https://user-images.githubusercontent.com/72760579/103259547-dc374180-4967-11eb-9284-725cf8df7ec6.png)
Do not merge yet, please :)

2020-12-29 04:56 UTC, GarboMuffin commented on addons/project-info/userscript.js
> +  const getBlockCount = async () => {
This doesn't need to be a async, infact being async will make it run extremely slow (relatively) in Firefox

2020-12-29 07:31 UTC, apple502j requested changes

2020-12-29 07:31 UTC, apple502j commented on addons/project-info/addon.json
> +  "traps": true,
This is no longer used

2020-12-29 08:22 UTC, mxmou commented
> I'm just dealing with this order...
> ![image](https://user-images.githubusercontent.com/72760579/103259547-dc374180-4967-11eb-9284-725cf8df7ec6.png)

You can add `order: 1` and it will always be on the end. It would also be a good idea to add some padding between the last button and the label.

2020-12-29 15:13 UTC, TheColaber commented
> order: 1

Where should I put that?

2020-12-29 15:18 UTC, TheColaber commented
Ah, You mean css, thx

2020-12-29 20:22 UTC, j5155 commented
nice but could it also show by the sprite and script count without editing the project?

2020-12-29 20:22 UTC, TheColaber commented
> nice but could it also show by the sprite and script count without editing the project?

it already does on the project page

2020-12-31 06:16 UTC, j5155 commented
> > nice but could it also show by the sprite and script count without editing the project?
> 
> it already does on the project page

no? 
![image](https://user-images.githubusercontent.com/54331556/103397289-36f5a800-4ae4-11eb-9063-00215356e61e.png)
I mean it would be cool if block count was shown here, unless that's what script count is and I'm dumb

2020-12-31 14:43 UTC, TheColaber commented
> > > nice but could it also show by the sprite and script count without editing the project?
> > 
> > 
> > it already does on the project page
> 
> no?
> ![image](https://user-images.githubusercontent.com/54331556/103397289-36f5a800-4ae4-11eb-9063-00215356e61e.png)
> I mean it would be cool if block count was shown here, unless that's what script count is and I'm dumb

Oh sorry, I read your question wrong the first time. I mean that would be cool but 1) It doesn't fit, and if we make the font even smaller it will be too hard to read 2) I would think that because this value edits so frequently, that it's the only one that should go in the editor.

2021-01-01 21:27 UTC, WorldLanguages approved these changes

2021-01-01 21:27 UTC, merged