Fix double scrollbar in popup
ScratchAddons/ScratchAddons pull request #1145
Opened 2020-12-31 14:17 UTC by mxmou

**Resolves**

Resolves #600 (finally)

**Changes**

Removes the double scrollbar in the popup when browser zoom is set to more than 100%. I don't like the solution because it uses JavaScript, but I don't know how else I could fix it. I also changed the height of the messaging tab so there is no scrollbar unless there are many messages.

**Reason for changes**

#600

**Tests**

I was able to zoom up to 175% before the second scrollbar appeared.

2020-12-31 19:16 UTC, WorldLanguages commented
Huh, it works - care to explain why?

2020-12-31 19:17 UTC, WorldLanguages approved these changes

2020-12-31 19:18 UTC, WorldLanguages commented
> Huh, it works - care to explain why?

If I wasn't clear enough - it would be cool to understand why this works?

2020-12-31 19:24 UTC, mxmou commented
> Huh, it works - care to explain why?

`100vh` doesn't work in popups the way one would expect, so I had to use JavaScript. `window.innerHeight` returns the height of the browser window or, in this case, the popup, but it has to be called after it loads, otherwise it would be 0.

I have no idea why the magic numbers I used have these values -- I just got them by testing.

2020-12-31 19:30 UTC, WorldLanguages commented
lol fine, it works, let's not touch it

2020-12-31 19:33 UTC, WorldLanguages commented
Unfortunately this does not work Firefox. There are scrollbars in both axis at 100% zoom level :(

2020-12-31 19:34 UTC, WorldLanguages requested changes
Firefox support pending

2021-01-01 19:55 UTC, mxmou commented
@WorldLanguages Fixed it by making the popup 1px smaller.

2021-01-01 21:20 UTC, WorldLanguages commented
Lol, this PR is a joke, but thanks for taking the time to fix this

2021-01-01 21:20 UTC, merged