better-quoter fixes
ScratchAddons/ScratchAddons pull request #1193
Opened 2021-01-04 14:13 UTC by apple502j

- fixes a crash
- fixes scrolling to wrong location

2021-01-04 16:28 UTC, WorldLanguages approved these changes

2021-01-05 09:52 UTC, pufferfish101007 requested changes

2021-01-05 09:52 UTC, pufferfish101007 commented on addons/better-quoter/userscript.js
> +      let blockpost = quoteButton.closest(".blockpost");
Can you add a `.querySelector(".post_body_html")` (should work) on the end of here so edit timestamps , siggies and user info can't be quoted? Thanks.

2021-01-05 13:06 UTC, RedGuy12 commented
I've wanted to quote siggies a few times tho....
________________________________
From: Pufferfish101007 <notifications@github.com>
Sent: Tuesday, January 5, 2021 3:53:04 AM
To: ScratchAddons/ScratchAddons <ScratchAddons@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [ScratchAddons/ScratchAddons] better-quoter fixes (#1193)


@pufferfish101007 requested changes on this pull request.

________________________________

In addons/better-quoter/userscript.js<https://github.com/ScratchAddons/ScratchAddons/pull/1193#discussion_r551825786>:

> @@ -4,13 +4,19 @@ export default async function ({ addon, global, console }) {
     let quoteButton = await addon.tab.waitForElement(".postquote a", { markAsSeen: true });
     quoteButton.setAttribute("onclick", "return false");
     quoteButton.addEventListener("mouseup", (e) => {
-      let blockpost = e.path.find((e) => e.classList.contains("blockpost"));
-      if (window.getSelection().toString().length)
-        textarea.value += `[quote=${
-          blockpost.querySelector(".black.username").innerText
-        }]${window.getSelection().toString()}[/quote]`;
+      let blockpost = quoteButton.closest(".blockpost");


Can you add a .querySelector(".post_body_html") (should work) on the end of here so edit timestamps , siggies and user info can't be quoted? Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/ScratchAddons/ScratchAddons/pull/1193#pullrequestreview-561651130>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOT5DEXMPIZWWSHD6IDHFZDSYLOQBANCNFSM4VTCHZ3A>.

2021-01-05 13:10 UTC, pufferfish101007 commented
> I've wanted to quote siggies a few times tho....

That's understandable, but it shouldn't be possible to quote half siggies and half posts as it is currently. When I make my pr for correct bbcode quoting I'll add that in as an optional setting unless apple does it in this one first.

2021-01-05 13:21 UTC, merged