Custom Font
ScratchAddons/ScratchAddons pull request #1764
Opened 2021-03-09 18:35 UTC by ErrorGamer2000

**Resolves**

Resolves #

**Changes**

**Reason for changes**

**Tests**

2021-03-09 18:43 UTC, ErrorGamer2000 commented on addons/custom-fonts/userscript.js
> -    !(function () {
Not deleted, just minified.

2021-03-09 18:48 UTC, ErrorGamer2000 commented on addons/custom-fonts/userscript.js
> -    })();
Not deleted, just minified to make the rest of the code easier to find.

2021-03-09 19:50 UTC, ErrorGamer2000 commented
No, there aren't yet. I am also adding bold and italic options for smaller fonts. And yes, an extension like this would work for any site... but people don't necessarily want it for other sites as well.

2021-03-09 20:11 UTC, ErrorGamer2000 commented
Added bold and italic options.

2021-03-09 21:14 UTC, RedGuy12 requested changes

2021-03-09 21:14 UTC, RedGuy12 commented on addons/custom-fonts/userscript.js
> +    !function(){function t(t,n,i){return t.call.apply(t.bind,arguments)}function n(t,n,i){if(!t)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){va
move to a library

2021-03-09 21:14 UTC, RedGuy12 commented on addons/custom-fonts/addon.json
> +    "description": "Change the fonts on Scratch! Uses google's WebFont loader. Only fonts avaliable on google fonts (and from google) can be used. Find the font you like then paste the name into the
"Uses google's WebFont loader. Only fonts avaliable on google fonts (and from google) can be used. Find the font you like then paste the name into the box!" is a little long...

Suggested new description: "Customize the font. Pick any font from https://fonts.google.com/ and type it below."

2021-03-09 21:16 UTC, ErrorGamer2000 commented on addons/custom-fonts/userscript.js
> +    !function(){function t(t,n,i){return t.call.apply(t.bind,arguments)}function n(t,n,i){if(!t)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){va
okay

2021-03-10 20:16 UTC, TheColaber commented
@ErrorGamer2000 Like W_L said we cannot accept this because, many other extensions (https://chrome.google.com/webstore/detail/font-customizer/fhoncdcfffaplldeekejehabjefniidh?hl=en for example) are built just for doing this. 
> however an addon like this would work on any site
So I think it's better to just download a separate extension.

2021-03-10 20:28 UTC, closed without merging