Add dark mode to statics graphs
ScratchAddons/ScratchAddons pull request #2037
Opened 2021-03-31 19:40 UTC by TheColaber

Try on https://scratch.mit.edu/statistics/
![image](https://user-images.githubusercontent.com/72760579/113201350-65943380-9237-11eb-9907-3b2b1b2f5892.png)

2021-03-31 19:51 UTC, mxmou requested changes
Could you also change the color of the grid lines? Maybe white for the black one and `#333` for the gray ones.

2021-03-31 19:51 UTC, mxmou commented on addons/dark-www/experimental_statistics.css
>    color: #575e75;
You can remove this line and line 6.

2021-03-31 19:53 UTC, mxmou commented on addons/dark-www/experimental_statistics.css
> +  background: #000;
Use `#282828`

2021-03-31 20:04 UTC, TheColaber commented
I think it's a bit hard to see at `#000000`
![image](https://user-images.githubusercontent.com/72760579/113203818-7f834580-923a-11eb-8797-935669c210b0.png)
I think `#606060` is better maybe
![image](https://user-images.githubusercontent.com/72760579/113204017-bc4f3c80-923a-11eb-8352-95eab2e9a361.png)

2021-04-01 07:40 UTC, mxmou approved these changes

2021-04-08 04:50 UTC, merged