Add Storage API
ScratchAddons/ScratchAddons pull request #2483
Opened 2021-05-13 13:47 UTC by TheColaber

**Resolves**

Resolves #1653

**Changes**

Creates API

**Reason for changes**

For the future to not use localStorage in addons anymore.

**Tests**

I tested by testing in 60FPS and scratch-messaging and both worked so yay.

2021-05-13 13:53 UTC, apple502j commented
Please don't mess with storages for now, big changes coming soon

2021-05-13 13:54 UTC, TheColaber commented
> big changes coming soon

big changes?

2021-11-27 14:24 UTC, RedGuy12 requested changes

2021-11-27 14:24 UTC, RedGuy12 commented on addon-api/common/Storage.js
> + * Manages settings.
*storage

2022-05-05 11:04 UTC, Norbiros commented
Any progress on this? Why it is waiting? What else needs to be done?

2022-05-05 13:18 UTC, RedGuy12 commented
> Any progress on this? Why it is waiting? What else needs to be done?

@Norbiros because


> Please don't mess with storages for now, big changes coming soon

2022-05-05 15:12 UTC, Norbiros commented
Soon > year? Okay... Can i know what changes and when they gonna be added?

2022-05-07 19:34 UTC, WorldLanguages commented
I forgot what changes those were, but I find it unlikely we'll add an API for this before the manifest v3 migration

2022-08-15 00:53 UTC, TheColaber commented
Closing since we'll have to deal with mv3 later anyway and this is outdated.

2022-08-15 00:53 UTC, closed without merging