Rewrite `editor-searchable-dropdowns` and add a "Add" Button for broadcasts dropdowns
ScratchAddons/ScratchAddons pull request #2761
Opened 2021-06-12 15:11 UTC by TheColaber

Resolves #2753

### Changes

Problem... I need to do something about __...

2021-06-12 16:25 UTC, GarboMuffin requested changes

2021-06-12 16:25 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.js
>      }
remove all of this, no longer necessary and causes issues

2021-06-12 16:25 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.js
> +    const arrowAtTop = oldDropDownDivShow.call(this, owner, ...args);
you have to return this at the end

2021-06-12 16:25 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.js
>      blocklyDropdownMenu = null;
do all of this in ScratchBlocks.DropDownDiv.clearContent instead

2021-06-12 16:25 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.js
> +      const variable = Blockly.getMainWorkspace().createVariable(searchBar.value, "broadcast_msg");
people should not be able to create broadcasts with empty names

2021-06-12 16:25 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.js
> +      // Hover somehow
any reason you can't use fake mouse events, the way it used to?

2021-06-12 16:31 UTC, GarboMuffin requested changes

2021-06-12 16:31 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.css
> +  margin-right: 5px;
margin-left on the button instead

2021-06-12 16:55 UTC, GarboMuffin commented
Also the dropdown div is used for not just dropdowns, but also direction and color pickers. Make sure those still work (they don't)

2021-06-12 19:37 UTC, GarboMuffin commented
What if instead of a button by the search bar, you did something like:

![image](https://user-images.githubusercontent.com/33787854/121787160-303a8900-cb8a-11eb-993d-d6326ad2fb80.png)

Where that would always be at the bottom of a search. People would be able to use arrows and pressing enter to select it, as they would any other item. You could have separate "Create global variable Y" and "Create local variable X" items for variables.

Also, up and down arrows are currently broken

2021-06-13 00:20 UTC, GarboMuffin requested changes
this is cool

More thoughts:

 - Should "new message" be hidden when something is searched?
 - Maybe rename and delete variable should be hidden as well?
 - See if "create variable" etc. can be hidden if nothing searched

2021-06-13 00:20 UTC, GarboMuffin commented on addons/editor-searchable-dropdowns/userscript.js
> +      console.log(block);
remove

2021-06-13 00:20 UTC, GarboMuffin commented on addons-l10n/en/editor-searchable-dropdowns.json
> +  "editor-searchable-dropdowns/createBroadcast": "Create broadcast \"{name}\""
The closest string in Scratch is "New message", so perhaps "Create message"? Not sure.

2021-06-13 12:24 UTC, TheColaber commented
> Maybe rename and delete variable should be hidden as well?

I had an idea to make these two items live update just like the others so you could rename the variable by just typing something in?

2021-06-22 20:58 UTC, WorldLanguages commented
Sry for taking long whats the status of this? :P

2021-06-23 01:14 UTC, TheColaber commented
I'm on vacation rn but I know this PR can
A. get merged - no problems at all
B. implement my suggestion above and then get merged

2021-07-01 04:52 UTC, GarboMuffin commented
@TheColaber merge https://github.com/TheColaber/ScratchAddons/pull/24 and then I think this is done unless you plan to add more features

2021-07-02 21:57 UTC, WorldLanguages commented
Can anything be done about the width of the dropdown?
![image](https://user-images.githubusercontent.com/17484114/124332197-44f5b580-db67-11eb-9dea-6516b9a21d10.png)

2021-07-02 22:02 UTC, WorldLanguages commented
AFAIK there's no easy solution. Unless we want the dropdown to grow as the user types more characters

2021-07-02 22:03 UTC, WorldLanguages approved these changes

2021-07-05 15:39 UTC, merged