debugger: fix more bugs
ScratchAddons/ScratchAddons pull request #2804
Opened 2021-06-16 22:46 UTC by GarboMuffin

- Fixes #2749
 - Fixes https://discord.com/channels/751206349614088204/755131743136383107/854819125770584065
 - Fix all other cases of console blocks not being called
 - Fixes addon sometimes not working when going from page page to editor
 - Fixes going to block not working immediately after leaving editor and returning to editor
 - Improve performance of logging items by probably close to 100x (the browser painting those items in the list is still painfully slow and always will be until it paginates or uses virtual lists, not something I want to do right now but might later if you want)
 - Fix unread logs icon not appearing reliably when a bunch of items are being logged (and also fix performance issues caused by that)
 - Activate the code tab when going to a block

2021-06-17 04:12 UTC, apple502j requested changes

2021-06-17 04:12 UTC, apple502j commented on addons/debugger/userscript.js
> +  extraContainer.addEventListener("wheel", (e) => {
needs to be passive

2021-06-17 04:12 UTC, apple502j commented on addons/debugger/userscript.js
> +  extraContainer.addEventListener("scroll", () => {
here too

2021-06-17 05:16 UTC, merged

2021-06-19 14:30 UTC, WorldLanguages commented on addons/debugger/userscript.js
> +    }
Block won't flash here, console will error `Cannot read property 'blockDragSurface_' of null` when calling `getRelativeToSurfaceXY()`. Block should either flash properly (setTimeout of 0?) or we should not try to make it flash.

2021-06-19 14:32 UTC, WorldLanguages commented on addons/debugger/userscript.js
> +
This is letting me drag the logs window exactly 1px more to the bottom that I should, resulting in a vertical scrollbar in the editor