editor-messages: add support for browser containers
ScratchAddons/ScratchAddons pull request #2942
Opened 2021-07-08 01:53 UTC by lisa-wolfgang

The current implementation of the addon gets the message count from the account that the messaging extension is signed in to. This works fine for most cases, but when Firefox's containers feature is utilized to sign in to an alt account, the message count does not show the correct number.

### Changes
The addon now determines which user is signed in to the editor tab and makes a direct API call to Scratch to get the message count.

### Reason for changes
An incorrect message count shouldn't be displayed near the alt's username:

![image](https://user-images.githubusercontent.com/43426138/124849737-eebcb400-df64-11eb-87ad-7eaa85d9c114.png)

### Tests
The addon continues to work as expected in browsers without container functionality.

2021-07-08 08:15 UTC, apple502j commented
I'm sure there are so many things that can break with this. Maybe we need to re-design the core.

2021-07-08 15:36 UTC, lisa-wolfgang commented
The worst thing that can happen is the message count turning to `NaN`, which would only happen if the API couldn't be connected to, so the likelihood of something actually breaking is extremely slim.

To cover the case of the API being unavailable, the message count could either not show (which is the same behavior as the extension badge and the same behavior as before) or display a red badge with an exclamation point that on click/hover would tell the user that the message count is currently unavailable. I'm going ahead with the first option for now.

2021-07-08 15:52 UTC, lisa-wolfgang commented
The Scratch API call is also cached by the browser, so this is even more of an edge case, but now all scenarios should be accounted for.

2021-07-08 17:42 UTC, RedGuy12 commented
we use `nocache=${Date.now()}` so caching is not a problem.
________________________________
From: lisa-wolfgang ***@***.***>
Sent: Thursday, July 8, 2021 10:52:20 AM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ScratchAddons/ScratchAddons] editor-messages: add support for browser containers (#2942)


The Scratch API call is also cached by the browser, so this is even more of an edge case, but now all scenarios should be accounted for.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/ScratchAddons/ScratchAddons/pull/2942#issuecomment-876552427>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOT5DET3VE6TFLOAHRIMIPTTWXCTJANCNFSM477YEYBA>.

2021-07-08 18:54 UTC, apple502j commented
We assume that the backend and frontend share the cookies globally; there's more that could break. For example, addons that use `addon.auth` API would break.

2021-07-08 18:58 UTC, RedGuy12 requested changes
tbh, i think it'd be better to figure out how to make `addon.account.getMsgCount()` supported with containers

2021-07-08 18:58 UTC, RedGuy12 commented on addons/editor-messages/userscript.js
> +    let user = document.querySelector("[class*='account-nav_profile-name']").innerHTML;
innerText

2021-07-08 19:04 UTC, mxmou commented on addons/editor-messages/userscript.js
> +    let user = document.querySelector("[class*='account-nav_profile-name']").innerHTML;
textContent

2021-07-08 21:17 UTC, WorldLanguages commented
@apple502j Can't we get the same message count that scratch-www uses with Redux? As long as the count is still fetched while inside the editor (if not, it would be useless for our usecase)

2021-07-09 08:32 UTC, apple502j commented
Closing for now; will do myself, with redux probably

2021-07-09 08:32 UTC, closed without merging