dark-www: fix `semicolon` addon showing white background and incorrect font color
ScratchAddons/ScratchAddons pull request #3068
Opened 2021-07-19 18:37 UTC by FunctionalMetatable

Resolves #1604

### Changes
Adds dark background to semicolon when both semicolon and dark-www addons are enabled.

### Tests
Tested locally

2021-07-19 19:09 UTC, mxmou commented
Apparently it always being light is the intended behavior. See #1297

2021-07-19 19:15 UTC, mxmou requested changes
I'll review the PR anyway because I think the semicolon should be dark in dark mode, like everything else.

2021-07-19 19:15 UTC, mxmou commented on addons/dark-www/experimental_scratchwww.css
> +  color: #fff !important;
Add `.semicolon` to the list of selectors (after `#donor`) instead of `!important` (which would likely break things).

2021-07-20 09:43 UTC, mxmou approved these changes

2021-07-20 15:46 UTC, WorldLanguages commented
@GrahamSH-LLK ?

2021-07-21 21:09 UTC, merged

2021-07-21 21:09 UTC, WorldLanguages commented
Well, if someone really wants to, they may PR to bring back semicolon white background on dark mode, but hopefully not :P