Implement Tab.createEditorContextMenu
ScratchAddons/ScratchAddons pull request #3429
Opened 2021-09-04 20:53 UTC by apple502j

Closes #3406 
Closes #3418 
Also adds new addon "Move costume to top or bottom" (move-to-top-bottom) - a testing addon but this can be kept.

2021-09-05 02:35 UTC, TheColaber commented on addon-api/content-script/Trap.js
> +  }
The folders addon could use this api.

2021-09-05 21:06 UTC, WorldLanguages commented
TODOs:
- [ ] Single contextmenu event for all addons
- [ ] Make sure this is compatible with right clicking sprite, costume and sound folders made by "folders" addon.

2021-09-08 09:54 UTC, apple502j commented
@WorldLanguages Requesting re-review; also @GarboMuffin for folders change and compat
After that I'll push the big boring changes (removing stuff from DevTools)

Not sure if I want to mess with folders addon in this PR. Maybe as a future refactoring PR.

2021-09-09 22:57 UTC, GarboMuffin commented
Folders change looks okay

2021-09-10 21:26 UTC, WorldLanguages commented on addon-api/content-script/Tab.js
> +    this._reactContextMenusInited = false;
These 2 look unused?

2021-09-10 21:58 UTC, TheColaber requested changes

2021-09-10 21:58 UTC, TheColaber commented on addons/move-to-top-bottom/userscript.js
> +  // Costumes should not be affected if user is running DevtoolsExtensio before version 1.20.0
"DevtoolsExtensio"

2021-09-11 15:04 UTC, merged

2021-09-11 16:01 UTC, mxmou commented
Shouldn't most references to "context menu" in the code, including the function name, actually be called "context menu item"?

2021-09-11 17:11 UTC, WorldLanguages commented
Yeah, it is this way to be consistent with `createBlockContextMenu` which has existed for a few months