Capitalise "Sign out"
ScratchAddons/ScratchAddons pull request #3581
Opened 2021-09-29 04:29 UTC by PoIygon

### Changes

I have changed the "Capitalize Account Settings" add-on so it also capitalizes "Sign out" button.
### Reason for changes

The changes should be made because the "Sign out" button is also not capitalized and it doesn't fit with the other buttons.
### Tests

I have tested this pull request by using the "load temporary add-on" feature in Firefox.

2021-09-29 22:19 UTC, WorldLanguages commented
@mxmou What do you think? Is there a specific reason you didn't do this too when submitting this addon initially?

2021-09-29 23:24 UTC, RedGuy12 requested changes
maybe this addon could also capitalize `Sign in` in the navbar?

2021-09-29 23:24 UTC, RedGuy12 commented on addons/account-settings-capitalize/addon.json
> +  "name": "Capitalized Account Settings and Sign Out",
```suggestion
  "name": "Capitalized account menu items",
```

2021-09-29 23:24 UTC, RedGuy12 commented on addons/account-settings-capitalize/addon.json
> +  "description": "Changes \"Account settings\" and \"Sign out\" in the account menu to \"Account Settings\" and \"Sign Out\".",
```suggestion
  "description": "Changes \"Account settings\" and \"Sign out\" in the account menu to \"Account Settings\" and \"Sign Out\", respectively.",
```

2021-09-29 23:24 UTC, RedGuy12 commented on addons/account-settings-capitalize/style.css
> +ul.user-nav > li:nth-child(3), .account-nav .dropdown > li:nth-child(3),
i think this is supposed to be
```suggestion
ul.user-nav > li:nth-child(3), .account-nav .dropdown > li:nth-child(4),
```
?

2021-09-30 06:44 UTC, mxmou commented
@WorldLanguages "Sign in" and, in the editor, "Fade in" and "Fade out" aren't capitalized either, so this would just make things less consistent.

2021-10-01 08:43 UTC, PoIygon commented
This is not active at all

2021-10-03 14:33 UTC, WorldLanguages commented
I'm unsure whether this change makes it more consistent or not.
`Account Settings` is obvious because the page title is title case:
![image](https://user-images.githubusercontent.com/17484114/135758507-50f95b6f-230f-44f0-b5b8-4d8d84259de7.png)
But if we capitalized `Sign Out`, then why not also capitalize `Sign in`? And we have an endless chain of consistency.

2021-10-03 14:33 UTC, closed without merging