FPS readout addon.
ScratchAddons/ScratchAddons pull request #3656
Opened 2021-10-14 08:39 UTC by Tacodiva

Idea from here: https://discord.com/channels/806602307750985799/806609030935740477/897971782076739635

This addon adds an FPS counter next to the green flag of a project player when enabled. Works fine with the 60fps plugin.

![image](https://user-images.githubusercontent.com/27910867/137281307-b1414969-c972-4efc-b642-2c31dcc51934.png)

Tested in Chromium on Ubuntu

2021-10-18 23:43 UTC, GrahamSH-LLK commented
the `=` is inconsistent.
we should use `:`

2021-10-20 03:57 UTC, Tacodude7729 commented
I don't know if that's super clear either. 'Lag', to me at least, seems like a bad you should always reduce, but a lot of CPU heavy projects run much faster if Scratch isn't yielding every 0.3 seconds to render the screen. You would also see things like turbo mode increasing 'lag', which doesn't really make sense. I think most people understand what FPS is, and people who don't probably don't have much use for the plugin anyways (if your gonna reduce it to just three categories it's kinda pointless because at that point people can just look at the project and see if it's laggy or not).
I think you're right about the description probably needing a bit more elaboration, though.

2022-01-06 04:13 UTC, lisa-wolfgang commented
@Tacodude7729 What will the fate of this addon be now that we have the epic and amazing debugger tabs?

2022-01-06 06:04 UTC, Tacodude7729 commented
@lisa-wolfgang I still think there's an argument to be made for this plugin. Seeing the FPS on the graph with the debugger isn't as simple as this, and it doesn't work when you're not in the editor like this does (it's also less performance heavy than the debugger). I would still vote that it should go in as an option for people (at least I would have it enabled), but I guess it's not really up to me :stuck_out_tongue:

2022-02-22 02:52 UTC, WorldLanguages commented
The FPS counter should hide itself in small stage mode.

Also, if I switch to another tab, then come back, I see the FPS counter go from ~10 FPS to 30 FPS pretty slowly. Since the drop of framerate is caused by changing tabs, could something be done about that?

Is the green color the same one as the green flag?

Should the FPS counter be visible in project player mode at all? Should it be togglable and the default be disabled?

2022-03-21 02:43 UTC, lisa-wolfgang commented
I'm pretty sure that the readout is the debugger-green color.

I think there's value in being able to see the FPS of a project from the project page, since performance is often better there. However, adding yet another button (plus this readout) seems like a lot of clutter for one feature, especially since we're already running out of room. Perhaps there could be an option to only see the FPS on your own projects?

2022-09-24 11:01 UTC, Tacodude7729 commented
Could I get some advice on what to do with this? I would prefer this PR gets closed or we work out what needs to be done for it to be merged, as I for some reason I made the changes on the master branch of my fork and it's annoying me that's it's still here lol.

2022-09-30 13:02 UTC, BroJac5246 commented
> Could I get some advice on what to do with this? I would prefer this PR gets closed or we work out what needs to be done for it to be merged, as I for some reason I made the changes on the master branch of my fork and it's annoying me that's it's still here lol. 

I can't say say for sure, but it looks like the main thing is to change when it displays.

2022-10-02 05:47 UTC, Mr-Anonymous75 commented
How about something like this for the design?
![](https://user-images.githubusercontent.com/73294041/193202374-669c4bab-6314-474a-acc5-7dbd68b01081.png)

2022-10-02 14:25 UTC, BroJac5246 commented
> How about something like this for the design?
> 
> ![](https://user-images.githubusercontent.com/73294041/193202374-669c4bab-6314-474a-acc5-7dbd68b01081.png)

I'm fine with it.

2022-10-02 14:43 UTC, lisa-wolfgang commented
The problem with that design is that it doesn't give the user enough info about what is being displayed. It's just a dial icon and a number.

2022-10-02 14:48 UTC, lisa-wolfgang commented
I still think it's worth looking into adding a very thin section below the stage and moving this there as well as the clone counter and mouse position. The controls bar isn't meant to display information -- that's why there was a separate bar for the mouse position in Scratch 2.

2022-10-02 20:55 UTC, lisa-wolfgang commented
Given the already low space in the project controls bar and the fact that this could be confused with the max FPS setting, I think it would be best to hold on merging this addon until a decision is made on https://github.com/ScratchAddons/ScratchAddons/issues/5155 (creating our own shared space somewhere below the stage.)

2022-10-21 12:00 UTC, Mr-Anonymous75 commented
> The problem with that design is that it doesn't give the user enough info about what is being displayed. It's just a dial icon and a number.

How about a show icon only toggle in the settings like the clone counter addon?

2023-04-15 00:48 UTC, Samq64 commented
Linking #2396 since the volume slider exists now.

2024-07-01 18:21 UTC, TheColaber commented
@Tacodiva @WorldLanguages Do you guys think this addon is good to be merged?

2024-07-07 01:16 UTC, Tacodiva commented
Ok I messed up git really bad because I tried to revert a prettier commit which messed everything up so I force pushed and then bad git things happend, but I think I've fixed it now. As for the actual contents of this PR, WL has some points I think need to be discussed:

>Should the FPS counter be visible in project player mode at all? Should it be togglable and the default be disabled?

and also

> Also, if I switch to another tab, then come back, I see the FPS counter go from ~10 FPS to 30 FPS pretty slowly. Since the drop of framerate is caused by changing tabs, could something be done about that?

I can't reproduce this second issue so someone who can might need to look into it.

2024-07-10 19:09 UTC, Samq64 reviewed
There's a small [shared library](https://github.com/ScratchAddons/ScratchAddons/blob/master/libraries/common/cs/small-stage.js) for handling small stage mode now.

2024-08-03 15:44 UTC, Samq64 commented
If there's still any interest in this I can take things from here.

2024-08-03 17:22 UTC, Samq64 commented
> Should the FPS counter be visible in project player mode at all? Should it be togglable and the default be disabled?

I thought the point of this addon over the debugger is that it can be used without the overhead of opening the editor. I guess it could be an option though.

> Also, if I switch to another tab, then come back, I see the FPS counter go from ~10 FPS to 30 FPS pretty slowly. Since the drop of framerate is caused by changing tabs, could something be done about that?

This happens with the debugger too:
[Screencast_20240803_131842.webm](https://github.com/user-attachments/assets/e4523283-b7d7-45a5-af29-82d41225d627)

2024-08-05 16:56 UTC, Samq64 approved these changes

2024-08-08 17:44 UTC, TheColaber commented
i changed the way it calculates the FPS, although I feel like it may be slightly inaccurate since sometimes the value goes above 60...

2024-08-08 20:00 UTC, Samq64 requested changes
When 60fps is enabled the counter says displays infinity.

2024-08-09 00:14 UTC, Tacodiva commented
> i changed the way it calculates the FPS, although I feel like it may be slightly inaccurate since sometimes the value goes above 60...

What was wrong with how it was calculated before?

2024-08-09 00:39 UTC, TheColaber commented
It felt a little "delayed"

2024-08-09 13:59 UTC, Samq64 commented
I can't repro any more but when exiting small stage it does display infinity but only for a second.

2024-09-05 23:43 UTC, TheColaber approved these changes

2024-09-05 23:44 UTC, TheColaber commented
ready to merge after updating versionAdded and fixing conflicts 🥳

2025-01-24 21:48 UTC, WorldLanguages commented on addons/fps/addon.json
> +  "versionAdded": "1.39.0"
```suggestion
  "versionAdded": "1.42.0"
```

2025-01-24 21:53 UTC, WorldLanguages commented on addons/fps/userscript.js
> +    if (fps !== lastFps || !wasRunning) fpsCounterElement.innerText = msg("fpsCounter", { fps: (lastFps = fps) });
The clone counter addon sets an HTML attribute instead of directly setting the text. One or the other may be more performant based on registered MutationObserver's including ours and ones added by other browser extensions.

2025-01-24 21:55 UTC, WorldLanguages approved these changes

2025-01-24 21:55 UTC, WorldLanguages commented
@Samq64 For some reason GitHub was bugging out, but it seems this had 2 approvals already, yours and Colaber's.

2025-01-24 22:01 UTC, WorldLanguages commented on addons/fps/addon.json
> +  "tags": ["editor", "projectPlayer", "featured"],
```suggestion
  "tags": ["editor", "player", "featured"],
```

2025-01-24 22:06 UTC, Samq64 commented
This still isn't the most accurate but it's good enough.

2025-01-24 22:07 UTC, Samq64 approved these changes

2025-01-26 15:36 UTC, merged