Add faster site messages update
ScratchAddons/ScratchAddons pull request #4006
Opened 2021-12-30 22:19 UTC by hello-smile6

Resolves #3974

### Changes

- Create addon with name `Faster site messages badge updating` in directory `addons/faster-site-messages-update`
- Configure userscript for previously mentioned addon
- Take code from other addons until it worked

### Reason for changes

- Scratch updates the message count on webpages every 30 seconds by default. Many users would prefer the message count to be updated more often. Since the update rate used for the extension icon (2500 milliseconds) seems to be an agreed-upon interval, I used the same timing for my addon.
- Users with touchscreens may prefer to use tablet mode. On Chrome OS, the URL bar is hidden at times in tablet mode. By updating the webpage's message count faster, those users will be able to respond to messages easier.

### Tests

- Tested on various pages with clean install, including on a user profile page, a studio page, and various forum pages. All of them worked perfectly.

### Additional credits
Thank you, @webdev03 , for making sure my work made at least some sense.

2021-12-30 22:29 UTC, hello-smile6 reviewed
Was `console.error()` right for this?

2021-12-30 23:04 UTC, hello-smile6 commented
I'm enabling actions, since it was necessary for https://github.com/ScratchAddons/ScratchAddons/pull/3986#issuecomment-1000318215, I assume it is necessary for me as well.

2021-12-31 22:48 UTC, hello-smile6 commented
@WorldLanguages Is there anything I need to change?

2022-01-02 20:57 UTC, WorldLanguages commented
> Since the update rate used for the extension icon (2500 milliseconds) seems to be an agreed-upon interval

This is misleading, see https://github.com/ScratchAddons/ScratchAddons/blob/master/background/handle-messages.js
`const COUNT_CHECK_INTERVAL = 30000;`

2022-01-03 20:41 UTC, RedGuy12 commented on addons/faster-site-messages-update/userscript.js
> +    if (msgCount === null && addon.settings.get("showOffline")) {
What's showOffline

2022-01-03 20:41 UTC, RedGuy12 commented on addons/faster-site-messages-update/userscript.js
> +        targetElement = document.querySelector(
Use waitForElement

2022-01-03 20:42 UTC, RedGuy12 commented on addons/faster-site-messages-update/userscript.js
> +      targetElement = null; // Garbage collection
Not necessary

2022-01-03 20:42 UTC, RedGuy12 requested changes
How often does the badge update currently?

2022-01-03 20:57 UTC, Samq64 commented
> How often does the badge update currently?

I think it might be every 30 seconds, but I'm not sure.

2022-01-04 08:31 UTC, webdev03 commented
https://github.com/ScratchAddons/ScratchAddons/pull/4006/commits/0441650ee8c4270bb2c8087d21a8c4a06a4ef10f _interesting_ commit description

Why don't you make the amount of time a setting, and make it so that you can't spam the API by making it at least 2000ms?

2022-02-08 09:44 UTC, apple502j commented
Don't think this is very useful. You can comment if you disagree.

2022-02-08 09:44 UTC, closed without merging

2022-02-08 13:37 UTC, GrahamSH-LLK commented
Also, this PR is abandoned.