Turbowarp redirect
ScratchAddons/ScratchAddons pull request #4479
Opened 2022-04-09 14:27 UTC by illogicalapple

### Changes
Added turbowarp redirect addon

### Reason for changes
Redirects unshared projects to Turbowarp

### Tests
I have tested it by installing a copy of Scratch Addons

2022-04-09 14:53 UTC, CST1229 commented on addons/turbowarp-redirect/addon.json
> +  "name": "Turbowarp redirect",
```suggestion
  "name": "TurboWarp redirect",
```
TurboWarp is a name.

2022-04-09 14:54 UTC, Norbiros requested changes

2022-04-09 14:54 UTC, Norbiros commented on addons/turbowarp-redirect/addon.json
> +  "enabledByDefault": true
I think it should be `false`.

2022-04-09 14:55 UTC, CST1229 commented on addons/turbowarp-redirect/addon.json
> +          "name": "Turbowarp"
```suggestion
  "description": "Redirects unshared projects to TurboWarp.",
  "tags": ["community"],
  "credits": [
    {
      "name": "illogicalapple",
      "link": "https://scratch.mit.edu/users/illogicalapple/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js",
      "matches": ["https://scratch.mit.edu/projects/*"]
    }
  ],
  "settings": [
  	{
      "name": "Redirect to",
      "id": "redirectUrl",
      "type": "select",
      "default": "//turbowarp.org/",
      "potentialValues": [
        {
          "id": "//turbowarp.org/",
          "name": "TurboWarp"
```
(also in these places)

2022-04-09 15:11 UTC, pufferfish101007 commented
Pretty sure this has been rejected for ethical reasons.

2022-04-09 15:38 UTC, Norbiros commented
> Pretty sure this has been rejected for ethical reasons.

I agree!

![Screenshot from 2022-04-09 17-36-29](https://user-images.githubusercontent.com/89837724/162580824-dfc291af-5c61-4b89-b787-dc8508cc9878.png)

I think it is in some kind "exploiting bug", scratch wanted to share projects, so you can hide them. They didn't block api, but when we are creating simple way to see unshared projects, it is not nice :-/. But as always, the last word belongs to W_L.

2022-04-09 15:42 UTC, mxmou commented
> Pretty sure this has been rejected for ethical reasons.

#510 is very similar to this PR and was rejected. #3222 suggests adding a link to an alternative player instead and is apparently not rejected.

2022-04-09 19:53 UTC, illogicalapple commented on addons/turbowarp-redirect/addon.json
> +  "enabledByDefault": true
Yes, I forgot about that, thanks! :)

2022-04-09 19:59 UTC, illogicalapple commented
> Pretty sure this has been rejected for ethical reasons.

https://docs.turbowarp.org/unshared-projects
Besides, there's [probably] no way you would be able to get a random project ID of a random unshared project without someone giving it to you.

2022-04-10 14:24 UTC, Chiroyce1 commented
Maybe some text on screen that says `Redirecting you to TurboWarp...` while it redirects? It will only be shown for <= 1 second(s) but still...

2022-04-10 15:02 UTC, Norbiros commented
![Screenshot from 2022-04-09 17-33-29](https://user-images.githubusercontent.com/89837724/162625814-c14b6ba7-c00b-407c-becb-1abcf795fadf.png)
I think that we can display scratch tool bar to, if you want to go back etc...

2022-04-10 16:53 UTC, WorldLanguages commented
"See deleted comments" and an addon like this were rejected by griffpatch back in 2020.

2022-04-10 16:53 UTC, closed without merging

2022-04-10 17:23 UTC, Norbiros commented
@WorldLanguages so please, close also #3222. If it is rejected  other issues like 3222 should be rejected too

2022-04-10 19:39 UTC, WorldLanguages commented
@Norbiros Thanks!

See #3222, I just posted more details about what addons griffpatch rejected in 2020.