Change logo and header colour on pre-release versions
ScratchAddons/ScratchAddons pull request #4810
Opened 2022-07-14 21:16 UTC by Samq64

Resolves #4805

### Changes

Turns the extension icon in the toolbar and extension popup and settings headers dark blue on pre-release vserisons. The extension icon shown elsewhere has to be manually changed through `manifesr.json` when bumping versions.

### Reason for changes

It makes it easier to identify pre-release versions of the extension.

### Tests

Tested on Chromium 103. The implementation isn't that great, but it works.

![image](https://user-images.githubusercontent.com/81489795/179087485-07033925-dbd0-4d9d-827e-20f184f3e352.png)

2022-07-14 22:17 UTC, RedGuy12 commented
You could set the icon in manifest.json to always be blue, then in .github/workflows/gen-manifest.js change it to the regular one

Also maybe export-ignore the blue logos? Would that only affect the release version or would it also affect the beta?

2022-07-15 06:28 UTC, mxmou commented
`--blue` (`#175ef8`) is slightly brighter and is meant to be used as a background color. Could that color be used instead?

2022-07-15 12:39 UTC, Samq64 commented
> `--blue` (`#175ef8`) is slightly brighter and is meant to be used as a background color. Could that color be used instead?

Sure. I didn't realize how dark this one was until I used it for the header.

2022-07-16 12:47 UTC, mxmou commented on webpages/popup/index.js
> +  document.getElementById("header").style.backgroundColor = "#175ef8";
This should be `var(--blue)`.

2022-07-16 12:47 UTC, mxmou commented on webpages/settings/index.js
> +    document.querySelector(".navbar").style.backgroundColor = "#175ef8";
This should also be `var(--blue)`.

2022-07-16 13:05 UTC, Samq64 commented
I wanted to make it clear it's a pre-release version on the popup, but it doesn't fit on one line. Should I put the version under the title?

2022-07-16 13:56 UTC, mxmou commented
> I wanted to make it clear it's a pre-release version on the popup, but it doesn't fit on one line. Should I put the version under the title?

Maybe `-pre` could be appended to the version number?

2022-07-18 20:23 UTC, Samq64 commented
> If feasible, we should change the "brand orange" used throughout the extension as well. (This would probably require a bit of CSS modification to reduce headache on version bump.)

OK. Should I reverse the blue and orange, or just change the orange?

2022-07-18 23:51 UTC, Samq64 commented
@lisa-wolfgang Done. I also made a transparent logo so I could remove the messy logo swapping code.

2022-07-19 04:49 UTC, Secret-chest commented
I think you should swap orange and blue, because the setting switches would look like addon switches.

2022-07-19 08:07 UTC, mxmou commented
> Changing everything to the blue would be best.

I think orange should stay in some places:
* the confirm button when importing settings
  ![image](https://user-images.githubusercontent.com/51849865/179699568-ed24e218-870a-48b1-8905-3bfaf8c2f677.png)
* messages from the ST

You could make a separate CSS variable for that - maybe `--danger-orange`.

2022-07-19 22:24 UTC, RedGuy12 requested changes
You still need to edit the workflow to change the icons back

2022-07-19 22:39 UTC, Samq64 commented
> You still need to edit the workflow to change the icons back
> 
> Also I don't think this works on licenses.html or permissions.html

Thanks, I forgot about those. Also, how do I test workflows?

2022-07-19 22:41 UTC, RedGuy12 commented
> Also, how do I test workflows?

you could just call the function in gen-manifest from the terminal because there main workflow we know works

2022-07-19 23:11 UTC, Samq64 commented
the favicon is still not blue, but it doesn't even seem to be located in this repo.

2022-07-19 23:20 UTC, RedGuy12 commented on .github/gen-manifest.mjs
> +  browser_action[default_icon] = "images/icon.png";
These all need to be quoted

2022-07-19 23:21 UTC, Samq64 commented on .github/gen-manifest.mjs
> +  browser_action[default_icon] = "images/icon.png";
Right, of course.

2022-07-19 23:28 UTC, RedGuy12 commented
> The favicon is still orange, but it doesn't even seem to be located in this repo.

We use `link[rel="icon"]` instead of `favicon.ico`

Also it's `manifest.browser_action` but with that fix, I tested and it works

2022-07-19 23:48 UTC, Samq64 commented
I found a race condition somewhere, but I don't run into it very often.

2022-07-19 23:56 UTC, RedGuy12 commented
What race condition?

2022-07-19 23:57 UTC, RedGuy12 approved these changes
Lgtm

2022-07-20 00:01 UTC, Samq64 commented
> What race condition?

About 1/4 of the time after reloading the extension, the primary colour isn't changed. Re-opeing the corrects it.

2022-07-20 05:46 UTC, Secret-chest commented
How does it look now?

2022-07-20 22:09 UTC, Secret-chest commented
Wow, I still think blue should be orange too

2022-07-20 22:14 UTC, Samq64 commented
> Wow, I still think blue should be orange too

I tried that, but reverted it because it turned things like links orange, and I didn't want to make another css variable, but I can do that if you want.

2022-07-21 05:14 UTC, Secret-chest commented
> > Wow, I still think blue should be orange too
> 
> I tried that, but reverted it because it turned things like links orange, and I didn't want to make another css variable, but I can do that if you want.

Links aren't the same blue.

2022-07-21 05:56 UTC, Hans5958 commented
A little bit offtopic: I see that you change it so the logo is transparent. This would make my idea of making the extension logo to be larger (as large as I did on the website) to be easier. I would follow it up on the next PR after this gets merged.

2022-07-21 05:57 UTC, Hans5958 approved these changes

2022-07-21 05:59 UTC, Hans5958 commented
Also, for the others, can we start doing a shorter `-pre` suffix on the manifest instead of the longer `-prerelease` suffix next time?

2022-07-21 07:03 UTC, mxmou commented
> > > Wow, I still think blue should be orange too
> > 
> > 
> > I tried that, but reverted it because it turned things like links orange, and I didn't want to make another css variable, but I can do that if you want.
> 
> Links aren't the same blue.

In light mode they are.

> A little bit offtopic: I see that you change it so the logo is transparent. This would make my idea of making the extension logo to be larger (as large as I did on the website) to be easier. I would follow it up on the next PR after this gets merged.

I don't think the logo should be much larger than the "Scratch Addons" title.

2022-07-21 16:57 UTC, WorldLanguages commented
> Also, for the others, can we start doing a shorter `-pre` suffix on the manifest instead of the longer `-prerelease` suffix next time?

`-prerelease` is valid semver

2022-07-22 00:54 UTC, Hans5958 commented
And so `-pre`. I wish it is shorter.

2022-07-31 13:38 UTC, merged