Refactor `image-uploader` a bit
ScratchAddons/ScratchAddons pull request #4814
Opened 2022-07-15 18:31 UTC by Weredime

### Changes
In `image-uploader`, use proper variable naming and merge code a bit more, use promises, etc.

### Reason for changes
Less work for the client, and better variable usage

### Tests
Tested on Firefox

2022-07-19 05:08 UTC, apple502j requested changes

2022-07-19 05:08 UTC, apple502j commented on addons/image-uploader/userscript.js
> +export default async function ({ addon, msg }) {
```suggestion
export default async function ({ addon, msg, console }) {
```

2022-07-19 05:08 UTC, apple502j commented on addons/image-uploader/userscript.js
> +    });
```suggestion
    file.arrayBuffer().then((buf) => uploadImage(buf, fileExt), (e) => {
      console.error("Error when reading file:", e);
      alert(msg("load-error"));
      progressElement?.remove();
    }));
```

2022-07-31 13:33 UTC, apple502j approved these changes

2022-10-01 10:30 UTC, jeffalo approved these changes
LGTM.

2022-10-01 14:47 UTC, merged