Extract find bar from dev-tools into a new addon
ScratchAddons/ScratchAddons pull request #4817
Opened 2022-07-16 00:31 UTC by TheColaber

Related to https://github.com/ScratchAddons/ScratchAddons/issues/3700

### Changes

Moved around code used for the dev tools find bar into a separate addon along with all of its files.

### Todo
- [ ] Finish migrating the CSS, I haven't finished yet
- [ ] Look at `DevTools.js` and make sure there are no extra functions
- [ ] Clean up code in find-bar addon
- [ ] Test 100 times
- [ ] Look at addon name and description
- [ ] Maybe add some settings to the addon?
- [ ] Enable this addon for everyone who previously had devtools enabled
- [ ] Probably indicate that this was moved out of the devtools addon.
- [ ] Make this enabled by default

Feel free to review if I've missed anything.

### Tests
This definitely needs to be tested by like 50 people before this gets merged, so please help out.

2022-07-16 00:54 UTC, Samq64 commented
The only problem I've noticed so far is that dark mode styles are broken. Other than that it looks pretty good.

![image](https://user-images.githubusercontent.com/81489795/179327922-870e417d-0ffe-4cd4-b62b-e55ad45e44fc.png)

2022-07-16 00:56 UTC, Samq64 commented
Also, the help button doesn't work anymore.

2022-07-16 01:28 UTC, TheColaber commented
> Also, the help button doesn't work anymore.

Yeah, I'm going to probably remove it since the addon is separate from devtools now.

2022-07-16 08:54 UTC, Weredime commented
the folder `blockly` should be put into `libraries` because multiple addons use it

2022-07-17 13:40 UTC, Samq64 commented
Is the find label next to the textbox necessary? The textbox placeholder already says that.

2022-07-17 13:45 UTC, Samq64 commented on addons-l10n/en/editor-devtools.json
>    "editor-devtools/bottom": "send to bottom",
Wasn't this removed from devtools a while ago?

2022-07-17 13:50 UTC, Samq64 commented on addons-l10n/en/find-bar.json
> +  "find-bar/tutorials": "Tutorials"
There are also unused now?

2022-07-17 15:46 UTC, TheColaber commented
> Is the find label next to the textbox necessary? The textbox placeholder already says that.

That can be changed in a later pr, this pr should keep everything relative the same as before.

2022-07-22 10:18 UTC, OregSamSas commented
~~I think it doesn't work if language is set to a language other than English. I don't know if it's because it needs translations now, If I remember right `devtools` didn't need them, and it worked fine for me even in Hungarian.~~
(My Chrome is in Hungarian, and because loading extensions in are not just temporarily in Chrome, I used that one and found this, maybe luckily)

> ---
**Ohh, UPDATE:
Only for Hungarian doesn't it work.**
I had a look at on what about other languages, and the result was it was fine for them. I don't what's going on with HU.
> ---

 I changed the language (at first I didn't need to, because it was automatically in Hungarian), then middle clicked one of the message hat blocks, and this was the result:
![image](https://user-images.githubusercontent.com/101597941/180412316-07b75345-6462-483c-8d9e-3005ea18999d.png)

I found out then that, there was only one event listed in the dropdown whose name was _"üzenet érkezésekor"_ which is the translation of "when I receive ..."
![image](https://user-images.githubusercontent.com/101597941/180412372-d2e11f76-0570-4deb-b86c-4394aaf753a6.png)

2022-07-22 11:28 UTC, OregSamSas commented
And it's not that easy. 
It works if I middle click on a stack event block, but middle clicking jumps to the "üzenet érkezésekor" event, but doesn't give any search results for it.

<html>
<details>
<summary>
screenshots
</summary>
<p><code>#1</code>:<br>
<img src="https://user-images.githubusercontent.com/101597941/180423454-3a348508-2e37-408a-b810-e7de3c604249.png" alt="1">
<br>
<p><code>#2</code>:<br>
<img src="https://user-images.githubusercontent.com/101597941/180429846-a0d0410c-051a-43a6-8252-1f5d2f980f1f.png">
</details>
<details>
<summary>
Also  the &quot;event <i>&uuml;zenet &eacute;rkez&eacute;sekor</i>&quot; always shows up in the dropdown list
</summary>
<img src="https://user-images.githubusercontent.com/101597941/180429137-2758e97a-d350-4d38-9b02-2bd3c57713f7.png">
</details>
</html>

2022-07-22 12:08 UTC, TheColaber commented
@OregSamSas Fixed! This bug existed before this PR was created. Thanks for reporting.

2022-07-22 20:47 UTC, Samq64 commented
I have a few suggestions:

* It would look better if the menu faded or had another animation when opening and closing it.
* I don't like the colour of highlighted items in the costumes and sounds tabs.
* When using the keyboard to scroll through items, the selected item can go offscreen. It should scroll the menu.
* When the find bar is enabled, but jump to block definition isn't, middle-clicking custom blocks should open it in the find bar like variables.

2022-07-23 05:09 UTC, Secret-chest commented
> It would look better if the menu faded or had another animation when opening and closing it.

It should roll down.

2022-07-23 09:58 UTC, mxmou commented
> * When the find bar is enabled, but jump to block definition isn't, middle-clicking custom blocks should open it in the find bar like variables.

This was already suggested here: https://github.com/ScratchAddons/ScratchAddons/issues/3700#issuecomment-1188246800

I also think this is something this PR should change.

> * It would look better if the menu faded or had another animation when opening and closing it.
> * I don't like the colour of highlighted items in the costumes and sounds tabs. Maybe something like Scratch blue in the costume editor, and pink in the sound editor would be better.
> * When using the keyboard to scroll through items, the selected item can go offscreen. It should scroll the menu.

Could you open issues for these?

> > It would look better if the menu faded or had another animation when opening and closing it.
> 
> It should roll down.

That would look weird because the popup opens behind the input, not under it.

2022-07-24 03:57 UTC, TheColaber commented
I implemented this table:
(thx lisa)
|   | **Middle-clicking non-definitions** | **Middle-clicking definitions**
| --- | --- | --- |
| **Find bar only** | Open in find bar | Open in find bar |
| **Jump to definition only** | Jump to definition | Do nothing |
| **Both** | Jump to definition | Open in find bar |

by polluting blockly which means this addon needs even more testing.

2022-07-24 14:17 UTC, Weredime commented
@TheColaber Since both `jump-to-def` and `find-bar` uses the `blockly` folder, why not put it in `libraries/cs`?

2022-07-24 14:45 UTC, TheColaber commented
No need to do so, it's fine for an addon to import other addon code like we do for the pause button and debugger.

2022-07-24 15:46 UTC, Weredime approved these changes
Tested and it works

2022-07-26 17:06 UTC, OregSamSas commented
I have a suggestion, what I tried to make, but I just wasn't enough smart to succeed. I found that the find bar stays there on the forth tab too (if the `variable-manager` is enabled), so if we could hide its own search bar and use `find-bar`'s one to jump to specific variables, this would be awesome. Because Find bar can be accessed by Ctrl+F, and it looks more good.

Below it can be checked, what I've managed to do. I couldn't complete it (the main part was very hard), because it would have needed the communication between two addon, and I couldn't use that one properly.

The special features that needs to be added that on clicking an item in the dropdown would jump to it's value input field, and on shift click it would jump into the name field, and focus on it automatically.

Maybe I should make an issue for this, but I feel it's just too late for that. I rather finish this comment.
<html>
<details>
<summary>concept</summary>
<img src="https://user-images.githubusercontent.com/101597941/181066279-76629f9d-3212-4035-a7f2-99ce988f4273.png"
</details>
</html>

2022-07-26 17:36 UTC, mxmou commented
@OregSamSas I don't think a separate addon should be required to search the list of variables.

2022-07-26 20:44 UTC, OregSamSas commented
Ok then just hide the find bar on the variable manager tab.

2022-07-27 03:22 UTC, TheColaber commented
I think the best thing to do would be to leave the list of items in the find bar empty.

2022-07-27 06:49 UTC, mxmou commented
> I think the best thing to do would be to leave the list of items in the find bar empty.

Why does it need to be visible if you can't use it to find anything?

2022-07-27 10:01 UTC, OregSamSas commented
> @OregSamSas I don't think a separate addon should be required to search the list of variables.

It wouldn't be required, it would add just some cool features for the searching on the `variable-manager` addon, IF both addon were enabled.
Reasons: it doesn't look good that you have multiple ways to search for an item in the variable+lists list, with a find-bar which technically wouldn't work (because it would just list nothing, according to the current state of this addon declared by Colaber⁽¹⁾), and a search bar, which doesn't jump to searched items, but hides the items which didn't match with the key. I'm not totally satisfied with that, I would prefer the find bar instead.

So basically the current search bar for variable-manager would stay the same in my suggestion, just a new (new, only for that tab) find-bar would be added to options. (If  searching for variables on the 4th tab was working, there should be a setting called: "Replace variable manager's built-in search bar", which would then hide that search bar, to use the find-bar, which has/would have more conveniences.)

If there's anything I'm wrong about, just let me know, because I could imagine, I've misunderstood your response.
And so sorry for not speaking understandably, it does really annoy me too, just I can't change it sadly :( .

⁽¹⁾ Here's the quote:
> I think the best thing to do would be to leave the list of items in the find bar empty.

2022-07-27 18:13 UTC, mxmou commented
> > Why does it need to be visible if you can't use it to find anything?
> 
> Following that logic, shouldn't Scratch hide the stop button icon if the project isn't running? I think it would be distracting if the find bar was hidden each time you switch to the variables tab.

It could also be disabled, but I don't think the reason why it's disabled would be obvious.

2022-07-28 04:34 UTC, apple502j commented
> Following that logic, shouldn't Scratch hide the stop button icon if the project isn't running?

FYI, stop button isn't just for stopping threads.

> I think it would be distracting if the find bar was hidden each time you switch to the variables tab.

I think it's fine.

2022-08-01 23:06 UTC, BroJac5246 commented
> I think it would be distracting if the find bar was hidden each time you switch to the variables tab.

I personally disagree, although that's just me.


>  Following that logic, shouldn't Scratch hide the stop button icon if the project isn't running?

That should be an addon [Goes to suggest it] ;)

2022-08-02 19:18 UTC, WorldLanguages commented
Note that we need griffpatch approval before merging this

2022-08-02 19:24 UTC, Weredime commented
> Note that we need griffpatch approval before merging this

@griffpatch

2022-08-02 20:22 UTC, griffpatch commented
Sure thing... Make it so.

On Tue, 2 Aug 2022 at 20:24, Weredime ***@***.***> wrote:

> Note that we need griffpatch approval before merging this
>
> @griffpatch <https://github.com/griffpatch>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ScratchAddons/ScratchAddons/pull/4817#issuecomment-1203122212>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABTM3PXIFCZIOFHASSKBVB3VXFYWPANCNFSM53XF6X2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-13 01:53 UTC, apple502j requested changes

2022-08-13 01:53 UTC, apple502j commented on addons/find-bar/addon.json
> +  "description": "Quickly find and jump to scripts, costumes and sounds in a sprite by clicking on the new find bar located to the right of sounds tab. Use the input to filter and your mouse or arrow
```suggestion
  "description": "Adds a find bar to find and jump to scripts, costumes and sounds next to the sounds tab. Use Ctrl + Left and Ctrl + Right in the code area to navigate to previous or next visited position after using the find bar.",
```

2022-08-13 01:53 UTC, apple502j commented on addons/jump-to-def/addon.json
> +  "description": "Using the middle mouse button or Shift + Click on a custom block allows you to jump to its definition.",
```suggestion
  "description": "Allows you to jump to a custom block's definition using the middle mouse button or Shift + Click on the block.",
```

2022-08-13 01:56 UTC, apple502j commented
Migration code is broken (version setter removed, see #4916 and also some code is messed up)

2022-08-13 08:36 UTC, apple502j approved these changes

2022-08-13 08:38 UTC, apple502j commented
:shipit:

2022-08-13 08:39 UTC, merged

2022-08-13 16:47 UTC, WorldLanguages commented on addons/editor-devtools/DevTools.js
> -                <div id="s3devToolBar">
I think you removed this without checking if other files reference this id.

This id should have been kept, it's referenced on Tab.js