better-emojis: refactor
ScratchAddons/ScratchAddons pull request #4830
Opened 2022-07-16 19:04 UTC by Weredime

Refactoring better-emojis to have:

- [ ] better code
- [ ] dynamic enable/disable

2022-07-16 19:59 UTC, apple502j commented on addons/better-emojis/addon.json
> +      "matches": ["projects", "studios", "https://scratch.mit.edu/users/*/"]
What happens to message pages?

2022-07-16 21:17 UTC, Weredime commented on addons/better-emojis/addon.json
> +      "matches": ["projects", "studios", "https://scratch.mit.edu/users/*/"]
Fixed

2022-07-16 21:36 UTC, Samq64 commented on addons/better-emojis/addon.json
> +      "matches": ["projects", "studios", "https://scratch.mit.edu/users/*/", "https://scratch.mit.edu/messages"]
```suggestion
      "matches": ["projects", "studios", "profiles", "https://scratch.mit.edu/messages"]
```

2022-07-17 07:08 UTC, Weredime commented on addons/better-emojis/addon.json
> +      "matches": ["projects", "studios", "https://scratch.mit.edu/users/*/", "https://scratch.mit.edu/messages"]
Done

2022-07-19 04:54 UTC, apple502j approved these changes

2022-07-19 04:54 UTC, apple502j commented on addons/better-emojis/userscript.js
> +      reduxCondition: (state) => state?.scratchGui.mode.isPlayerOnly,
Won't this crash in studios?

2022-07-19 04:55 UTC, apple502j requested changes
Wait, pressed the wrong button

2022-07-31 13:28 UTC, apple502j approved these changes

2022-08-02 19:46 UTC, WorldLanguages commented on addons/better-emojis/userscript.js
> +      reduxCondition: (state) => state?.comments.status.comments === "FETCHED",
`state` is guaranteed to be an object.

2022-08-02 19:47 UTC, WorldLanguages commented on addons/better-emojis/userscript.js
> +        emoji.dataset.emoji = emojiId;
Can we use `.dataset.saEmoji`?

2022-08-02 19:48 UTC, WorldLanguages commented
I wasn't aware this addon, when enabled, has always used a MutationObserver on the whole body on every page :S
Nice idea to refactor it!

2022-08-02 19:50 UTC, WorldLanguages commented on addons/better-emojis/userscript.js
> +      reduxCondition: (state) => state?.comments.status.comments === "FETCHED",
I think you meant the opposite?
`state.comments?.status?.comments`
Current code in your branch crashes on the messages page

2022-08-02 19:50 UTC, WorldLanguages requested changes
Doesn't work in the messages page

2022-08-02 20:55 UTC, Weredime commented
@WorldLanguages I've addressed your changes

2022-08-02 20:58 UTC, WorldLanguages approved these changes

2022-08-02 20:58 UTC, merged