Fix missing `reduxEvents`
ScratchAddons/ScratchAddons pull request #4851
Opened 2022-07-18 17:37 UTC by mxmou

Resolves #4829

### Changes

Fixes two bugs that would happen when changing the language:
* the costume editor would lose its dark background if dark mode was enabled
* the onion skin settings would disappear

2022-07-18 22:01 UTC, TheColaber approved these changes

2022-07-19 02:23 UTC, WorldLanguages requested changes
We should also consider File>Load (after getting `Replace contents of the current project?` prompt)

2022-07-19 18:44 UTC, WorldLanguages approved these changes

2022-07-19 19:22 UTC, Weredime approved these changes

2022-07-21 20:34 UTC, merged