Confirm leaving studio and removing project in mystuff
ScratchAddons/ScratchAddons pull request #4891
Opened 2022-07-24 13:02 UTC by Norbiros

Resolves #4884

### Changes

- Fix bug with showing "unshare project" when leaving/deleting studio in mystuff
- Show new delete confirmation when user is deleting project in mystuff (in trash, and in projects tab)
- Show leave studio confirmation when user is deleting or leaving studios

### Tests

Firefox 95.

### To Do:

- [ ] Add update note
- [ ] Maybe change message when user is deleting or leaving studio

2022-07-28 08:35 UTC, mxmou commented
studio-tools already shows a confirmation for leaving studios. It doesn't have to be duplicated in this addon.

2022-07-28 09:13 UTC, Norbiros commented
Oh, okay... Fixed

2022-07-28 09:45 UTC, mxmou requested changes

2022-07-28 09:45 UTC, mxmou commented on addons-l10n/en/confirm-actions.json
> +  "confirm-actions/removeproject": "Are you sure you want to remove this project?"
```suggestion
  "confirm-actions/removeproject-title": "Delete Project",
  "confirm-actions/removeproject": "Are you sure you want to delete this project?"
```

2022-07-28 09:45 UTC, mxmou commented on addons/confirm-actions/addon.json
>      }
Rename this to "Confirm deleting projects" and move it after "Confirm project unsharing".

I think it should be enabled by default.

2022-07-28 09:45 UTC, mxmou commented on addons/confirm-actions/userscript.js
> +      let isInStudios = document.querySelector("#tabs > :nth-child(4).active");
I think it's better to check `location.hash`.

2022-07-28 11:07 UTC, mxmou approved these changes

2022-07-31 13:54 UTC, apple502j approved these changes

2022-07-31 13:56 UTC, merged