forum-time-zones: use mobile forums instead of sdb
ScratchAddons/ScratchAddons pull request #4892
Opened 2022-07-24 16:28 UTC by Weredime

### Changes
Leaves the ScratchDB deprecated v2 APIs and get UTC dates using the mobile forums

### Reason for changes
Less bytes sent to client

### Tests
Firefox

2022-07-30 22:34 UTC, WorldLanguages requested changes
Doesn't work for me, it's showing UTC+0 (my timezone is UTC-3)
Did you forget to convert it to the user's time zone?

2022-08-02 19:32 UTC, WorldLanguages commented on addons/forum-time-zones/userscript.js
> +  const pageNumber = /page=(\d+)/.exec(location.search)?.[1];
`new URLSearchParams(location.search).get("page")` would be cleaner

2022-08-02 19:34 UTC, WorldLanguages approved these changes

2022-08-03 02:13 UTC, apple502j approved these changes

2022-08-03 02:13 UTC, merged