studio-followers: refactor
ScratchAddons/ScratchAddons pull request #4893
Opened 2022-07-24 19:11 UTC by Weredime

Refactors the `studio-followers` addon.
## Changes
- Remove `lib.js`, put everything in userscript
- Wait for user to be logged in
- Rename some selectors and IDs
- Basically refactor

2022-07-31 13:50 UTC, apple502j requested changes

2022-07-31 13:50 UTC, apple502j commented on addons/studio-followers/userscript.js
> +        addButton.removeEventListener("click", clickListener);
```suggestion
        userButton.removeEventListener("click", clickListener);
```

2022-07-31 14:59 UTC, apple502j approved these changes

2022-08-13 13:38 UTC, TheColaber approved these changes

2022-08-14 10:49 UTC, merged