hide-flyout: Fix a couple bugs
ScratchAddons/ScratchAddons pull request #4903
Opened 2022-07-25 21:43 UTC by GarboMuffin

- The lock button is now inside the flyout SVG instead of being "on top" of it which allows us to remove some styles without breaking things
 - Fixes #4896
 - Also fixes dragged sprites not appearing over the target pane
 - Removed unnecessary .gui from selectors as some Scratch mods don't have an element with that class

(marked as draft pending some additional testing later today)

2022-07-27 05:30 UTC, GarboMuffin commented
Scope ended up growing larger than anticipated. I've tried pretty hard to break this with combinations of hide-flyout, editor-stage-left, columns, and RTL but haven't found anything yet (though I'm sure I broke something)

2022-07-27 10:05 UTC, mxmou requested changes

2022-07-27 10:05 UTC, mxmou commented on addons/hide-flyout/style.css
> +  transform: translate(calc(var(--sa-flyout-width) - 15px - 32px), 4px);
The previous 4px vertical offset included the top border of the `.injectionDiv`, so this should now be 3px.

2022-07-27 17:15 UTC, mxmou approved these changes

2022-07-30 22:13 UTC, WorldLanguages approved these changes
Fixes the bug and more, thanks garbo and mxmou

2022-07-30 22:14 UTC, merged