Allow adding list items through variable-manager by pressing enter
ScratchAddons/ScratchAddons pull request #4912
Opened 2022-07-27 15:23 UTC by Samq64

Resolves #3235

### Changes

Removes the shift key check from variable manager and replaces it with an element type check.

### Reason for changes

The shift key doesn't have to be held while pressing enter to create new list items.

### Tests

Tested on Chromium 103. Pressing enter on a variable input still unfocuses it.

2022-07-31 13:40 UTC, apple502j requested changes
Needs to be noted on latestUpdate/description/whatever

2022-07-31 20:18 UTC, Samq64 commented
I was thinking `Shift+Enter` could be used to inset new items above like Scratch, but maybe that's not such a good idea.

2022-08-04 03:01 UTC, apple502j commented on addons/variable-manager/addon.json
> +    "temporaryNotice": "List items can now be inserted without holding shift."
```suggestion
    "temporaryNotice": "List items can now be inserted without holding the Shift key."
```

2022-08-04 03:01 UTC, apple502j approved these changes

2022-08-12 22:57 UTC, TheColaber approved these changes

2022-08-12 22:58 UTC, merged