Add support for scratchblocks to full-signature
ScratchAddons/ScratchAddons pull request #4917
Opened 2022-07-28 10:43 UTC by Norbiros

Resolves #3684
Continues #4217 (I forgot about that PR...)

### Changes

Full areas addon now adds scrollbar to `scratch blocks 3` (from `scratchblocks` addon).

2022-07-28 12:52 UTC, Weredime requested changes

2022-07-28 12:52 UTC, Weredime commented on addons/full-signature/blocks.css
> +.sblocks3 {
Pretty sure it's `.blocks3`, not `.sblocks3`
```suggestion
.blocks3 {
```

2022-07-29 22:54 UTC, Chameleon-Coder reviewed
I agree with @Weredime - I think it's .blocks3, not .sblocks3
EDIT: I confused them

2022-07-30 13:34 UTC, Weredime approved these changes

2022-08-03 01:39 UTC, apple502j approved these changes

2022-08-03 01:39 UTC, merged