New addon: collapsing sprite properties
ScratchAddons/ScratchAddons pull request #5158
Opened 2022-10-03 23:44 UTC by lisa-wolfgang

Resolves #4970 (more or less)

### Changes

Users on small screens rejoice: you're about to get double the sprite grid space!

![A screenshot of the sprites area with the addon enabled. The sprite properties panel has been hidden, leaving more room for the sprites grid.](https://user-images.githubusercontent.com/43426138/193700940-039ffd60-7227-4292-9151-30fc152fad14.png)

When this addon is enabled, the sprite properties panel is hidden by default. The panel can be shown again by double-clicking a sprite tile.

When the "don't collapse panel on load" option is enabled, when the page is loaded or when the addon is enabled, the sprite properties panel will stay showing until it is closed manually.

When the "automatically collapse when mouse leaves sprite panel" option is enabled, the sprite properties panel will automatically hide once the mouse leaves the area encompassing both the properties panel and the sprites grid.

https://user-images.githubusercontent.com/43426138/193704748-02b1185a-c0d8-4c9a-9304-d9ed9028600a.mp4

### Reason for changes

Users with small screens currently have difficulty accessing the sprites grid, especially when there are many sprites per project. This addon attempts to alleviate that by increasing the available sprites grid space by over a factor of 2.

### Tests

Tested to work on Chromium 106.

2022-10-04 01:06 UTC, Samq64 commented
What about people on tablets or chromebooks with bad touchpads? They probably don't have problems double-clicking, but there's still probably a better way.

2022-10-04 01:07 UTC, Samq64 commented
What about people on tablets or chromebooks with bad touchpads? They probably don't have problems double-clicking, but there's still probably a better way.

2022-10-04 01:07 UTC, Samq64 commented
What about people on tablets or chromebooks with bad touchpads? They probably don't have problems double-clicking, but there's still probably a better way.

2022-10-04 01:38 UTC, BroJac5246 commented
> What about people on tablets or chromebooks? They might not have problems double-clicking, but there's probably still a better way.

Good point. This could get awkward for tablets or Chromebooks in tablet mode. I wonder if some sort of "show sprite properties panel" button could be beneficial. It would expand the sprite properties panel when clicked or hovered over.

2022-10-04 02:40 UTC, lisa-wolfgang commented
I think it would be best to avoid adding such a button, since it would have the considerable tradeoff of subtracting space from the sprites grid area, which would reduce the efficacy of this addon. I did consider adding a "properties" button to each sprite's context menu, but double-tapping is much easier to perform for tablet users than long-holding (the current way to access context menus on touchscreens) and then tapping the option. If the concern is about accidentally hitting the delete button, touchscreen users will have likely already enabled the deletion confirmation and/or delete button hiding addons for when they need to select sprites normally.

2022-10-04 02:50 UTC, lisa-wolfgang commented
I'm actually not sure to what extent Scratch Addons supports (or should support) touchscreen devices. As mentioned earlier, touchscreen Chromebooks certainly do exist, and we support Scratch Addons on Chrome. I'm going to create an issue for this, but I don't think that it's a merge-blocker.

2022-10-04 03:03 UTC, lisa-wolfgang commented
On a somewhat related note, because of this addon's usefulness to users with small screen sizes and its classification as a 2.0-like feature, I would like to propose that this addon receive the `featured` tag.

2022-10-04 13:29 UTC, lisa-wolfgang commented
Thinking about it some more, it might be best to include an option that keeps the name bar showing and have this enabled by default. There is otherwise no UI-indicated way to edit a sprite's name.

2022-10-04 19:46 UTC, BroJac5246 commented
> I think it would be best to avoid adding such a button, since it would have the considerable tradeoff of subtracting space from the sprites grid area, which would reduce the efficacy of this addon.

I was thinking it could be like the backpack's button: short and wide. You could choose if the button shows through the addon settings, and it would help compensate for the disappearance of the sprite properties panel while causing minimal additional disturbance.

2022-10-05 17:20 UTC, Secret-chest commented
> Thinking about it some more, it might be best to include an option that keeps the name bar showing and have this enabled by default. There is otherwise no UI-indicated way to edit a sprite's name, unless an info button is added like in Scratch 2.0.

Why not allow editing it from the name displayed below the thumbnail? When clicked it would turn into an input.

2022-10-05 19:38 UTC, BroJac5246 commented
> > Thinking about it some more, it might be best to include an option that keeps the name bar showing and have this enabled by default. There is otherwise no UI-indicated way to edit a sprite's name, unless an info button is added like in Scratch 2.0.
> 
> Why not allow editing it from the name displayed below the thumbnail? When clicked it would turn into an input.

Probably double clicked, but good idea. 👍

2022-10-05 23:05 UTC, lisa-wolfgang commented
> Why not allow editing it from the name displayed below the thumbnail? When clicked it would turn into an input.

That's a possible option, but keep  in mind that there is very little horizontal space inside a sprite tile.

2022-10-06 17:10 UTC, Secret-chest commented
> > Why not allow editing it from the name displayed below the thumbnail? When clicked it would turn into an input.
> 
> That's a possible option, but keep  in mind that there is very little horizontal space inside a sprite tile.

Well, the input could be minimal, like the Windows Explorer double-click to rename.

2022-10-09 00:43 UTC, joshpinto6 commented
This is a great feature!

2022-10-09 11:44 UTC, Secret-chest commented
Also, can you make an animation?

2022-10-13 02:46 UTC, lisa-wolfgang commented
Given that the input doesn't necessarily need to be confined to the dimensions of the sprite tile, I do like the idea of double-clicking a sprite's name to quickly edit it. However, this feature would likely fit better in a new addon. Most users wouldn't expect to find this specific feature inside of an addon whose primary feature is to collapse the properties panel.

2022-10-13 02:51 UTC, lisa-wolfgang commented
I'd still like to add an "info" button on the currently selected sprite that shows the properties panel, as well as a "close" button on the properties panel itself, to make this addon more user-friendly. These added UI elements will not be configurable.

2022-10-13 02:51 UTC, BroJac5246 commented
> However, this feature would likely fit better in a new addon. Most users wouldn't expect to find this specific feature inside of an addon whose primary feature is to collapse the properties panel.

I agree. Perhaps that addon could also have an option to remove the sprite name input- that way, if someone doesn't quite want this addon, they could at least make the sprite properties panel smaller.

2022-10-16 22:50 UTC, GarboMuffin requested changes
The animation does not work in Firefox

And in all browsers, if I have something like this:

![image](https://user-images.githubusercontent.com/33787854/196062176-5f1767ef-9293-4bc7-a245-235b396850cb.png)

double clicking in the area under Sprite1 where there isn't any sprite does not work to show the menu

2022-10-17 02:32 UTC, lisa-wolfgang commented
@GarboMuffin I don't think I've touched anything relevant since you reviewed, but the animation works fine in Firefox from my testing on the latest commit -- could you reconfirm that it doesn't work for you?

2022-10-17 02:34 UTC, lisa-wolfgang commented
Besides fixes to any additional bugs discovered, I no longer have any changes I wish to make in this PR.

2022-10-17 03:10 UTC, GarboMuffin commented
Animation is working fine now, isn't that funny

Addon currently breaks when you leave the editor and go back inside

2022-12-03 01:31 UTC, WorldLanguages commented
@GarboMuffin Do you think this PR could be mergeable as-is? (regarding functionality and bugs)

2022-12-03 08:25 UTC, GarboMuffin approved these changes

2022-12-03 22:20 UTC, WorldLanguages commented on addons/sprite-properties/addon.json
> +      "name": "Collapse panel on load",
I think we could use a better term than "on load" here

2022-12-03 22:21 UTC, WorldLanguages commented on addons/sprite-properties/addon.json
> +      "name": "Collapse panel on load",
onion-skinning uses `Enable by default` for pretty much the same setting meaning.
We could use that or maybe `Collapse panel by default`

2022-12-03 22:22 UTC, WorldLanguages commented
> On a somewhat related note, because of this addon's usefulness to users with small screen sizes and its classification as a 2.0-like feature, I would like to propose that this addon receive the `featured` tag.

I agree!

2022-12-03 22:23 UTC, WorldLanguages commented on addons/sprite-properties/addon.json
> +  "tags": ["editor"],
TODO: add featured tag

2022-12-03 22:25 UTC, WorldLanguages commented on addons/sprite-properties/userscript.js
> +  const propsCloseBtnClass = "sa-sprite-properties-close-btn";
We could use `SNAKE_CASE` for these constants

2022-12-03 22:27 UTC, WorldLanguages commented on addons/sprite-properties/addon.json
> +  "versionAdded": "1.29.0",
1.30.0

2022-12-06 01:54 UTC, WorldLanguages submitted a review, later dismissed
There's a bug (setting "COLLAPSE PANEL BY DEFAULT" enabled):
Go to scratch.mit.edu/create and wait for the project to load. The "i" icon will appear when the panel is expanded, instead of when it's collapsed, which is the opposite of what normally happens.

2022-12-06 02:40 UTC, lisa-wolfgang commented
Could not repro in browser with Chromium 107.

2022-12-10 16:44 UTC, mxmou commented
The arrow for closing it isn't very noticeable. Could it be centered below the bottom row of properties?

2022-12-14 21:17 UTC, WorldLanguages commented
Merging: PR author is an org member + 1 approval

2022-12-14 21:17 UTC, merged

2022-12-14 21:18 UTC, WorldLanguages commented
> The arrow for closing it isn't very noticeable. Could it be centered below the bottom row of properties?

You may create an issue or a PR.

2022-12-14 21:18 UTC, WorldLanguages commented
Low prio bug I dismissed was moved to issue #5443

2022-12-21 16:19 UTC, WorldLanguages commented
> The arrow for closing it isn't very noticeable. Could it be centered below the bottom row of properties?

@mxmou Reminder!