New addon: More costume fonts
ScratchAddons/ScratchAddons pull request #5344
Opened 2022-11-11 15:28 UTC by valmontechno

An add-on that adds the following fonts to the costume editor.
Scratch, Arial, Helvetica, Verdana, Impact and Monospace.

2022-11-11 17:23 UTC, BroJac5246 commented
Related:
#2050 (so this is _probably_ rejected)
#3059

2022-12-17 18:38 UTC, TheColaber requested changes

2022-12-17 18:38 UTC, TheColaber commented on addons/more-costume-fonts/userscript.js
> +	function addNewFont(font, previousFont, modContextMenu) {
Can you just add a check for `if (!addon.self.disabled) return` at the top of this function and then add `dynamicEnable` and `dynamicDisable` in the addon.json, so the addon can be turned on and off dynamically?

2022-12-17 18:38 UTC, TheColaber commented on addons/more-costume-fonts/userscript.js
> +		button.className = addon.tab.scratchClass('button_button') + ' ' + addon.tab.scratchClass('font-dropdown_mod-menu-item');
I think you can just use `addon.tab.scratchClass('button_button', 'font-dropdown_mod-menu-item')`

2022-12-17 18:38 UTC, TheColaber commented on addons/more-costume-fonts/userscript.js
> +		if (elem.classList.contains(addon.tab.scratchClass('font-dropdown_mod-context-menu')) && elem.classList.contains(addon.tab.scratchClass('input-group_input-group'))) {
Won't the first part of this if statement always be true? `font-dropdown_mod-context-menu` is already in the waitForElement, and waitForElement should guarantee that class will exist on the element.

2022-12-17 18:38 UTC, TheColaber commented on addons/more-costume-fonts/addon.json
> +			"text": "Some fonts may not be compatible with all devices.",
Could you tell us what they will and won't work with and why?

2022-12-17 18:38 UTC, TheColaber commented on addons/more-costume-fonts/userscript.js
> +			elem.textContent = '';
Is it really necessary to clear the element's previous items and then re-add them in?

2022-12-17 18:38 UTC, TheColaber commented on addons/more-costume-fonts/userscript.js
> +		{ 'name': 'Monospace', 'family': 'Monospace' }
Are there any other fonts that work natively in the scratch editor? How can we find out?

2022-12-17 20:30 UTC, Secret-chest commented
@valmontechno @BroJac5246 @TheColaber Remember not all devices are guaranteed to have these fonts (example Linux)!

2022-12-17 23:20 UTC, Samq64 commented
> Remember not all devices are guaranteed to have these fonts (example Linux)!

Aa a linux user I think it's fine as long as there's a notice like we alreay do for the more keys addon.

2022-12-18 07:47 UTC, Secret-chest commented
> > Remember not all devices are guaranteed to have these fonts (example Linux)!
> 
> As a linux user I think it's fine as long as there's a notice like we alreay have for the more keys addon.

I don't want to have to see text that is cut off!

2022-12-18 07:47 UTC, Secret-chest commented
Also Scratch will get removed.

2022-12-18 09:45 UTC, mxmou commented
This doesn't solve any of the problems previous suggestions for custom fonts had. These fonts (except Scratch) only work if they're installed on the user's device - most of them are only available on Windows and macOS. As @Secret-chest pointed out, a fallback font will be used on other platforms, which sometimes causes text to be cut off or otherwise broken.

Monospace is a generic font name that can refer to any monospace font, which causes similar issues.

2022-12-19 16:07 UTC, WorldLanguages commented
This is probably rejected, so I'm closing this PR to avoid any misunderstandings.

2022-12-19 16:07 UTC, closed without merging