Rename the "more links" addon
ScratchAddons/ScratchAddons pull request #5375
Opened 2022-11-27 00:27 UTC by DNin01

Resolves #4882

### Changes

Changed the name of the "More links" addon to "Clickable external links" and edited the description.

### Reason for changes

The new name makes more sense.

### Tests

Changes should work fine.

2022-11-28 14:38 UTC, RedGuy12 approved these changes

2022-11-29 22:46 UTC, WorldLanguages commented
I think @Hans5958 would like to be pinged here

2022-12-01 01:28 UTC, Hans5958 commented
This is an artifact when names can be abstract and doesn't have to be descriptive. I disagree with this kind of handling (Names can, and should be able to, be abstract like "Scratch Messaging"), so I'm going to neither approve nor disapprove this PR.

2022-12-01 08:01 UTC, mxmou requested changes
Searching for "more links" still shows this addon because the ID is `more-links`. That won't work in other languages, so I think the keywords "more" and "link" should be included in the description.

Another option is to leave the old name and only change the description.

2022-12-01 19:40 UTC, DNin01 commented
Alright, I'll change the name back but keep the new description.

2022-12-02 07:35 UTC, mxmou approved these changes

2022-12-02 13:31 UTC, RedGuy12 commented
> This is an artifact when names can be abstract and doesn't have to be descriptive.

Personally, I like the descriptive names. In any case, most addons have descriptive names so this addon should have one too.



> Searching for "more links" still shows this addon because the ID is `more-links`. That won't work in other languages, so I think the keywords "more" and "link" should be included in the description.

I think that we should add a `keywords` field to addon manifests for search purposes. This has been discussed in the past but never in depth.



> Alright, I'll change the name back but keep the new description.

Just because someone says "an *option* is xyz," does NOT mean you have to immediately change it! It's better to first discuss all the available options and agree on one together before implementing any.

2022-12-02 18:18 UTC, WorldLanguages commented
> I think that we should add a `keywords` field to addon manifests for search purposes. This has been discussed in the past but never in depth.

Translating single words, without context, is not an easy task. The "keywords" field is an obvious missing feature until you consider the perspective of translators.
Do we have an issue number for this feature? Or should we create one?

2022-12-02 18:42 UTC, CST1229 commented
> Translating single words, without context, is not an easy task. The "keywords" field is an obvious missing feature until you consider the perspective of translators.

That's why message descriptions exist.

2022-12-02 18:48 UTC, WorldLanguages commented
> That's why message descriptions exist.

Yes, we can add message descriptions now. But this should be discussed in a separate issue, not here.

2022-12-02 23:27 UTC, WorldLanguages approved these changes

2022-12-02 23:27 UTC, merged

2022-12-02 23:28 UTC, WorldLanguages commented
See #4387 for discussion regarding keywords.

2023-07-02 20:55 UTC, DNin01 commented
> Searching for "more links" still shows this addon because the ID is `more-links`. That won't work in other languages, so I think the keywords "more" and "link" should be included in the description.

Coming back to this, why is this important?

Although I undid the name change to resolve this problem, I still think it would be a good idea to change the name as I don't think it's as self-explanatory as it should be. I mean, technically, it fits because you have clickable links for more URLs, but there are other things the current name could mean.

2023-07-02 22:30 UTC, WorldLanguages commented
> Coming back to this, why is this important?

I think the idea is to avoid the pain of searching for the old addon name, and not getting any results. Users would expect that after enabling an addon, they can search for the addon name as they remember it, right? We sometimes fix this by including the keywords from the old name on the addon description

2023-07-02 22:32 UTC, DNin01 commented
> > Coming back to this, why is this important?
> 
> I think the idea is to avoid the pain of searching for the old addon name, and not getting any results. Users would expect that after enabling an addon, they can search for the addon name as they remember it, right? We sometimes fix this by including the keywords from the old name on the addon description

It'd still have one of the two original words, though. The only thing that would happen in that case is that it wouldn't be as high in the search results.

2023-07-03 04:50 UTC, mxmou commented
> > I think the idea is to avoid the pain of searching for the old addon name, and not getting any results. Users would expect that after enabling an addon, they can search for the addon name as they remember it, right? We sometimes fix this by including the keywords from the old name on the addon description
> 
> It'd still have one of the two original words, though. The only thing that would happen in that case is that it wouldn't be as high in the search results.

Searching for two keywords only shows addons that have both in their title or description.

2023-07-03 10:19 UTC, Secret-chest commented
An alternative would be to add a `keywords` JSON field.

2023-07-03 19:50 UTC, DNin01 commented
> An alternative would be to add a `keywords` JSON field.

Maybe we could start adding keywords for just a few addons in exceptions like these.

2023-07-04 04:55 UTC, BroJac5246 commented
> An alternative would be to add a `keywords` JSON field.

I've been thinking about that as well.

2023-07-04 15:02 UTC, WorldLanguages commented
Yeah, that is #4387