TTS Captions
ScratchAddons/ScratchAddons pull request #5514
Opened 2022-12-29 23:49 UTC by GrahamSH-LLK

### Changes

Adds text to speech captions
<img width="980" alt="image" src="https://user-images.githubusercontent.com/64214252/210021884-2f6140f0-05fd-4453-b478-3c5e63ef6570.png">

### Reason for changes

It's widely requested and is a good "accessibility" patch on our shoulder
### Tests

Yes

2022-12-30 02:36 UTC, retronbv commented
you seem to have left your sanity check in there

2022-12-30 12:02 UTC, fractioneater commented
Shouldn't this have the community tag?

2022-12-30 12:19 UTC, mxmou commented
> Shouldn't this have the community tag?

Indeed - that's why schema validation is failing.

2022-12-30 17:46 UTC, Secret-chest commented
Could the [Sprite] tag be bold or something?

2022-12-30 22:23 UTC, mxmou commented
> Could the [Sprite] tag be bold or something?

Is it even necessary? Text spoken by different sprites doesn't sound different in vanilla Scratch.

2023-01-01 17:25 UTC, Secret-chest commented
> > Could the [Sprite] tag be bold or something?
> 
> Is it even necessary? Text spoken by different sprites doesn't sound different in vanilla Scratch.

It would be to distinguish it. Maybe make all sprite tags the same size so text gets aligned nicely.

2023-01-01 17:32 UTC, BroJac5246 commented
> > Could the [Sprite] tag be bold or something?
> 
> Is it even necessary? Text spoken by different sprites doesn't sound different in vanilla Scratch.

Maybe showing it should be a setting.

2023-01-01 17:42 UTC, CST1229 commented
> Is it even necessary? Text spoken by different sprites doesn't sound different in vanilla Scratch.

What about e.g different characters with different voices?

2023-01-02 12:30 UTC, Hans5958 commented
Weak opinion: The style of the captions needs to be done better. Something like [Google Meets' captions would work](https://workspaceupdates.googleblog.com/2019/04/live-captions-in-meet.html) comes in my mind, but anything works really.

2023-05-06 14:32 UTC, mybearworld requested changes
My first review on GitHub, so I've probably done everything wrong. Also, the addon has just stopped working for me locally, so I can't really check if changes break anything.

2023-05-06 14:32 UTC, mybearworld commented on addons/tts-captions/addon.json
> +  "tags": ["projectPage"],
This should have the community tag, as mentioned in https://github.com/ScratchAddons/ScratchAddons/pull/5514#issuecomment-1367882657.

```suggestion
  "tags": ["community", "projectPage"],
```

2023-05-06 14:32 UTC, mybearworld commented on addons/tts-captions/userscript.js
> +  logView.placeholderElement.textContent = "no logs";
This should probably use `msg`.

2023-05-06 14:32 UTC, mybearworld commented on addons/tts-captions/style.css
> +}
This is never used.

```suggestion
```

2023-05-06 14:32 UTC, mybearworld commented on addons/tts-captions/userscript.js
> +import createLogView from "../debugger/log-view.js";
Does this really need to use debugger? I think this is overcomplicating it.

2023-05-06 22:25 UTC, GrahamSH-LLK commented
This doesn't work for dynamic values like joins and variables

2023-05-06 22:25 UTC, closed without merging

2023-05-06 23:54 UTC, WorldLanguages commented
I'm going to create an issue for this suggestion
Here it is: #6016