Add message indicator color option for website dark mode and customizable colors
ScratchAddons/ScratchAddons pull request #5602
Opened 2023-01-11 17:07 UTC by actuallyronan

### Changes

Adds a color setting to the "Website Dark Mode and Customizable Colors" add-on that lets you select the color for the message indicator.

### Reason for changes

Many people (including myself) would prefer to be able to change the color of the message indicator, as it is a key part of the Scratch website.

### Tests

Tested on Chrome 108 and it seems to work.

2023-01-11 17:47 UTC, mxmou requested changes
You don't need to define a `customCssVariable` for this - one will be created automatically based on the setting name (`--darkWww-messageIndicatorColor` in this case).

2023-01-11 17:47 UTC, mxmou commented on addons/dark-www/experimental_scratchr2.css
> +}
```suggestion
#topnav ul.account-nav .messages .notificationsCount {
  background-color: var(--darkWww-message-indicator-color); 
}
```

2023-01-11 17:47 UTC, mxmou commented on addons/dark-www/experimental_scratchwww.css
> +}
```suggestion
#navigation .messages .message-count.show {
  background-color: var(--darkWww-message-indicator-color); 
}
```

2023-01-12 16:54 UTC, Samq64 commented
Could you please enable actions? (https://github.com/actuallyronan/ScratchAddons/actions)

2023-01-12 18:54 UTC, DNin01 commented
> Could you please prettier on the actions page? (https://github.com/actuallyronan/ScratchAddons/actions)

I think it's not that Prettier isn't working, it's that it's not turning tab characters into two spaces.

@actuallyronan could you change all the tab characters to two spaces?

2023-01-12 20:28 UTC, actuallyronan commented
> > Could you please prettier on the actions page? (https://github.com/actuallyronan/ScratchAddons/actions)
> 
> I think it's not that Prettier isn't working, it's that it's not turning tab characters into two spaces. The CGs already recommend enabling workflows, so they probably already enabled it.
> 
> @actuallyronan could you change all the tab characters to two spaces?

Done

2023-01-12 23:04 UTC, DNin01 reviewed
> Done

Thanks!

Also, sorry to bug you _again_, but another formatting thing in the `addon.json` is that there is usually a space after the `:` right after each key (example: `"key": "value"`), so maybe change that as well, to keep the formatting consistent with other files.

2023-01-12 23:04 UTC, DNin01 commented on addons/dark-www/addon.json
> +      "name":"Message indicator color",
The messages "indicator" is also known as the messages badge.

2023-01-13 08:45 UTC, mxmou commented
@actuallyronan Formatting is now fixed.

2023-01-14 18:01 UTC, DNin01 requested changes
Four things:
1. You ~~need to~~ might want to add the default message badge color to the other presets (look under `"presets": [`).
2. This doesn't apply to the messages page itself.[^1]
3. If you set the badge color to a bright color, the number on it should turn black.
4. This is generally known as the messages badge.

[^1]: See image: 
![An orange messages badge on the Messages page](https://user-images.githubusercontent.com/106490990/212488150-1745e26e-a301-4b1d-b414-2982fc8d133c.png)

2023-01-14 18:11 UTC, mxmou commented
> You need to add the default message badge color to the other presets (look under `"presets": [`).

This isn't actually necessary, but it's probably a good idea - I think it makes sense to reset the color when selecting a preset.

2023-01-15 00:44 UTC, Samq64 commented
Are there any other orange/yellow elements on the site that could be customized with this setting?

2023-01-15 00:53 UTC, DNin01 commented
> Are there any other orange/yellow elements on the site that could be customized with this setting?

The Share button.

2023-01-15 01:14 UTC, DNin01 commented
> > You need to add the default message badge color to the other presets (look under `"presets": [`).
> 
> This isn't actually necessary, but it's probably a good idea - I think it makes sense to reset the color when selecting a preset.

The reset menu for that color will look like this, though.

![The preset color choices menu with transparent backgrounds from the presets](https://user-images.githubusercontent.com/106490990/212504020-ce04ce29-1edf-4c99-9f9a-5128c1d5e307.png)

Clicking on one of them, however, still resets the color to the default, not a transparent background as shown.

2023-01-15 07:37 UTC, mxmou commented
> > > You need to add the default message badge color to the other presets (look under `"presets": [`).
> > 
> > 
> > This isn't actually necessary, but it's probably a good idea - I think it makes sense to reset the color when selecting a preset.
> 
> The reset menu for that color will look like this, though.
> 
> ![The preset color choices menu with transparent backgrounds from the presets](https://user-images.githubusercontent.com/106490990/212504020-ce04ce29-1edf-4c99-9f9a-5128c1d5e307.png)
> 
> Clicking on one of them, however, still resets the color to the default, not a transparent background as shown.

That's a bug with the settings page.

2023-01-15 16:17 UTC, WorldLanguages commented
> That's a bug with the settings page.

Could you create a GitHub issue about it? (I think it doesn't exist yet)

2023-01-15 17:26 UTC, mxmou commented
@WorldLanguages I'll just open a PR to fix it - it's a very simple change.

2023-01-24 08:09 UTC, mxmou commented
If a light color is chosen, the message count should become black. You can use `customCssVariables` to implement this.

2023-02-06 22:09 UTC, WorldLanguages commented
@mxmou We should probably move this to the v1.32 milestone?

2023-04-09 04:30 UTC, Secret-chest commented
What about the Explore orange?

2023-04-09 09:13 UTC, mxmou commented
> What about the Explore orange?

That should probably be in a separate addon for customizing banner colors, similar to #4187.

2023-04-29 20:09 UTC, WorldLanguages commented
What's the status of this PR?

2023-04-30 07:40 UTC, mxmou commented
> What's the status of this PR?

This feature is still missing:

> If a light color is chosen, the message count should become black. You can use `customCssVariables` to implement this.

2023-06-30 01:17 UTC, DNin01 commented
Scratch changed the message counter background in the update. Do we need to worry about making it customizable anymore? If not, I'll close this.

2023-06-30 01:20 UTC, DNin01 commented
Well, there is the fact that some people might not like it to be dark red.

This PR isn't being actively maintained right now, so maybe we can start a new one if anyone is interested.

2023-06-30 01:32 UTC, WorldLanguages commented
> Well, there is the fact that some people might not like it to be dark red.

There were one of two people sending feedback about this. Maybe it could be part of this addon.

2023-06-30 07:34 UTC, mxmou commented
> > Well, there is the fact that some people might not like it to be dark red.
> 
> There were one of two people sending feedback about this. Maybe it could be part of this addon.

The option this PR currently adds changes both counters - the one in the navigation bar and the one on the Messages page. It should probably be split into two.

2023-06-30 14:37 UTC, DNin01 commented
> > > Well, there is the fact that some people might not like it to be dark red.
> 
> > 
> 
> > There were one of two people sending feedback about this. Maybe it could be part of this addon.
> 
> 
> 
> The option this PR currently adds changes both counters - the one in the navigation bar and the one on the Messages page. It should probably be split into two.

That would work, but it feels like too much. I wonder how we could implement this while only adding one color to the settings.

2023-07-03 21:56 UTC, WorldLanguages commented
> I don't think there's a (good) way to make both colors customizable with just one setting.

I agree. It would be nice if we could provide a `Scratch default colors (blue)` preset (or maybe another name) for this addon.
@mxmou It's up to you if you want to work on this PR or create a new one

2023-07-03 22:05 UTC, DNin01 commented
I don't feel like customizing the badge above the list of messages counting the number of unread messages is as important. If we were to go with a one-setting method, I'd allow customizing the badge on the navigation bar and not the one on the messages page.

2023-07-03 22:59 UTC, WorldLanguages commented
From feedback:

> you forgot the option to change the message notifier from a putrid orange red to any color

2023-07-04 05:49 UTC, mxmou commented
> I don't feel like customizing the badge above the list of messages counting the number of unread messages is as important. If we were to go with a one-setting method, I'd allow customizing the badge on the navigation bar and not the one on the messages page.

People want to change the one on the messages page back to orange though.

2023-07-04 07:31 UTC, mxmou approved these changes

2023-07-04 15:41 UTC, WorldLanguages commented
Looks good!
Does this take into account that the scratchr2 message button orange is a slightly different shade? (Not saying it should, but I've checked whether they have the same exact hex code). Looks like it does. Nice!

2023-07-04 15:42 UTC, WorldLanguages commented
I guess this will need a settings migration for users who already selected these presets (specifically, the ones with `(blue)` in the name). I'd say we create an issue after merging this and deal with it later.

2023-07-04 15:48 UTC, WorldLanguages commented
(We should also add a latestUpdate so that users notice this update)

2023-07-04 18:39 UTC, DNin01 commented
Alright, this seems like the best we can do, and that's fine.

2023-07-04 21:04 UTC, WorldLanguages approved these changes

2023-07-06 12:39 UTC, merged