Replace "What I've been doing" with the user's statistics.
ScratchAddons/ScratchAddons pull request #5653
Opened 2023-01-20 19:20 UTC by Dr-Lego

### Replace "What I've been doing" with the user's statistics

- Data from ScratchDB and the Scratch Website
- Displays exact follower count (fetched from "scratch.mit.edu/users/[username]/followers")
- You can still switch beetween the Statistics and WIBD.
- Lets you instantly see the follower count, rank, etc. when you visit someone's profile page
- Adds also a link to the user's ScratchStats page
- Looks nice in dark and normal mode

### How it looks like:
![image](https://user-images.githubusercontent.com/119697525/213787157-3d1593d8-75b4-4d7d-bdcb-16e90e1690e7.png)

![image](https://user-images.githubusercontent.com/119697525/213785536-b7cf8b04-41c8-4219-a2cc-5bff33745b14.png)

![image](https://user-images.githubusercontent.com/119697525/213785434-9d7457cc-d4e2-44d9-b735-40c42d945deb.png)

2023-01-20 19:22 UTC, Dr-Lego commented
It says I should add "VersionAdded" to the addon manifest, but I'm not supposed to do that, I guess?

2023-01-20 20:21 UTC, DNin01 requested changes
> It says I should add "VersionAdded" to the addon manifest, but I'm not supposed to do that, I guess?

Add `"versionAdded": "1.31.0"` - that's the upcoming version. You can do this later if you want.

Also, if possible, make sure the addon supports [dynamic enable/disable](https://scratchaddons.com/docs/reference/addon-api/addon.self/#using-addonselfdisabled-and-events-dynamicdisable), meaning that the addon's effects disappear when disabled and appear when enabled, all without refreshing the page.

2023-01-20 20:21 UTC, DNin01 commented on addons/show-user-stats/addon.json
> +    "tags": ["community"],
```suggestion
    "tags": ["community"],
    "dynamicEnable": true,
    "dynamicDisable": true,
```

2023-01-20 20:32 UTC, mxmou commented
There's already an addon that displays statistics on profiles. It should probably be combined with this one.

2023-01-20 21:23 UTC, BroJac5246 commented
Can there be a setting to show WIBD by default?

2023-01-20 21:25 UTC, DNin01 commented
In addition to adding dynamicEnable and dynamicDisable to the addon manifest, I believe you might need to make some changes to the userscript to make it automatically revert the layout when you disable the addon and automatically apply when you enable it, without even refreshing the page, unless it already does that.

2023-01-20 22:51 UTC, WorldLanguages commented
> There's already an addon that displays statistics on profiles. It should probably be combined with this one.

Yeah, I'd prefer to see this as a setting for the `Profile statistics` addon.

2023-03-21 00:18 UTC, WorldLanguages commented
Does this provide any additional functionality not currently part of "profile statistics"?
Is the only difference that this isn't a new row, but instead uses the "What I've been doing" section? I just created an issue for that: #5834

2023-04-02 21:22 UTC, WorldLanguages commented
Closing PR because it creates a new addon with the same goal as an existing one.

Issue #5834 was created because some users might want a setting for the different positioning that this PR suggested.

2023-04-02 21:22 UTC, closed without merging