Prevent visited links from turning blue on messages page
ScratchAddons/ScratchAddons pull request #5714
Opened 2023-02-10 14:49 UTC by fractioneater

Resolves #5709

### Changes

Links that are visited no longer turn blue on the messages page when dark-www is enabled.

### Reason for changes

What's happening currently is inconsistent with the behavior of vanilla Scratch.

### Tests

Tested on a chromium browser.

2023-02-10 18:12 UTC, DNin01 approved these changes

2023-02-10 18:16 UTC, WorldLanguages commented
Looks like this does fix the issue, but there might be a better way to do so. Let's wait for mxmou review.

2023-02-11 08:23 UTC, mxmou requested changes

2023-02-11 08:23 UTC, mxmou commented on addons/dark-www/experimental_scratchwww.css
>  a.social-messages-profile-link:link,
Add `a.social-messages-profile-link:visited` here and remove the `:not()`s under "Link color" - they make selectors more specific, which will probably cause problems.

2023-02-11 11:42 UTC, mxmou approved these changes

2023-02-11 17:58 UTC, merged