Compact buttons
ScratchAddons/ScratchAddons pull request #5840
Opened 2023-03-23 13:12 UTC by StioStudio

Resolves #5839
(That it is to much text on the editor and the project page)

### Changes
*Hides all the text on the buttons: turbowarp, see inside, share, remix
*adds a icon to the share button

### Reason for changes
I don't like that it is so much text
I made this mostly for my self, but I thought I could send a pr

### Tests
Tested on oprea GX. It is fully CSS and I have not used any weird code.

2023-03-23 13:13 UTC, StioStudio commented
I forgot to take away the info page. Just take that away if you accept the pr :)

2023-03-23 16:04 UTC, BroJac5246 commented
> I forgot to take away the info page. Just take that away if you accept the pr :)

Please do it yourself or open a new PR. The removal of it would need to be reviewed, so do it now so we don't have to wait even longer later.

Also, in general you should find or create an issue before making a PR.

2023-03-23 16:35 UTC, StioStudio commented
> > I forgot to take away the info page. Just take that away if you accept the pr :)
> 
> Please do it yourself or open a new PR. The removal of it would need to be reviewed, so do it now so we don't have to wait even longer later.
> 
> Also, in general you should find or create an issue before making a PR.

Yeah sorry about that, but how do I hide the other addon from the pr?

2023-03-23 16:40 UTC, BroJac5246 commented
> > > I forgot to take away the info page. Just take that away if you accept the pr :)
> > 
> > Please do it yourself or open a new PR. The removal of it would need to be reviewed, so do it now so we don't have to wait even longer later.
> > 
> > Also, in general you should find or create an issue before making a PR.
> 
> Yeah sorry about that, but how do I hide the other addon from the pr?

Delete all the code from it. If you still want the code, then back it to a different branch.

2023-03-23 16:43 UTC, StioStudio commented
> > > > I forgot to take away the info page. Just take that away if you accept the pr :)
> > > 
> > > 
> > > Please do it yourself or open a new PR. The removal of it would need to be reviewed, so do it now so we don't have to wait even longer later.
> > > Also, in general you should find or create an issue before making a PR.
> > 
> > 
> > Yeah sorry about that, but how do I hide the other addon from the pr?
> 
> Delete all the code from it. If you still want the code, then back it to a different branch.

Ok I will see what I can do (I am not good with git and GitHub)

2023-03-23 18:31 UTC, DNin01 commented
> > > > > I forgot to take away the info page. Just take that away if you accept the pr :)
> 
> > > > 
> 
> > > > 
> 
> > > > Please do it yourself or open a new PR. The removal of it would need to be reviewed, so do it now so we don't have to wait even longer later.
> 
> > > > Also, in general you should find or create an issue before making a PR.
> 
> > > 
> 
> > > 
> 
> > > Yeah sorry about that, but how do I hide the other addon from the pr?
> 
> > 
> 
> > Delete all the code from it. If you still want the code, then back it to a different branch.
> 
> 
> 
> Ok I will see what I can do (I am not good with git and GitHub)

You can re-commit everything related to the compact buttons feature to a new branch in order to remove the extra unrelated commits, then create a new PR.

Be sure to include a link to the issue you created for this by typing `Resolves #` followed by the issue number.

2023-03-23 19:52 UTC, StioStudio commented
> > > > I forgot to take away the info page. Just take that away if you accept the pr :)
> > > 
> > > 
> > > Please do it yourself or open a new PR. The removal of it would need to be reviewed, so do it now so we don't have to wait even longer later.
> > > Also, in general you should find or create an issue before making a PR.
> > 
> > 
> > Yeah sorry about that, but how do I hide the other addon from the pr?
> 
> Delete all the code from it. If you still want the code, then back it to a different branch.

I fixed it

2023-03-23 19:53 UTC, StioStudio commented
@DNin01 thanks for the change in the "Resolves"

2023-03-23 20:35 UTC, StioStudio commented
Should I take away the "beta" tag

2023-03-23 20:37 UTC, StioStudio commented
And what should I set the "versionAdded" to? Should it be like 1.31.1 or maybe 1.31.2?

2023-03-24 01:03 UTC, DNin01 commented on addons/compact-buttons/addon.json
> +    "name": "Compact Buttons",
We don't usually use Start Case in addon names as of now.
```suggestion
    "name": "Compact buttons",
```

2023-03-24 01:03 UTC, DNin01 commented on addons/compact-buttons/addon.json
> +    "description": "Buttons in projects get smaller/more compact",
Might want to further clarify this.
```suggestion
    "description": "Turns the text on some buttons on project and editor pages into icons to save space.",
```

2023-03-25 10:19 UTC, StioStudio commented
So is this gonna be accepted?

2023-03-25 19:36 UTC, StioStudio commented
Hello?

2023-03-25 19:58 UTC, Samq64 commented
> So is this gonna be accepted?

Probably, but it might be a while before this is reviewed.

2023-03-25 20:40 UTC, StioStudio commented
> > So is this gonna be accepted?
> 
> Probably, but it might be a while before this is reviewed.

Oh ok

2023-03-25 22:20 UTC, WorldLanguages commented
So this also involves creating our own icons for existing buttons that lack an icon, right?

2023-03-25 22:43 UTC, StioStudio commented
> So this also involves creating our own icons for existing buttons that lack an icon, right?

Yes. For now that is only the share button that I made a icon for (made it in like 2 minutes, so it is not that good).

2023-03-25 23:00 UTC, WorldLanguages commented
@StioStudio That makes this a bit more complex, because we need to find suitable icons that can be understood 🤔

2023-03-25 23:04 UTC, StioStudio commented
> @StioStudio That makes this a bit more complex, because we need to find suitable icons that can be understood 🤔

My icons works pretty good

2023-03-25 23:06 UTC, StioStudio commented
> @StioStudio That makes this a bit more complex, because we need to find suitable icons that can be understood 🤔

Btw if you want to see the icon: https://github.com/ScratchAddons/ScratchAddons/pull/5840/files#diff-4677ea56a0fb5544a11b4475a31d26ee65d6f3717437d66f4e28f5d151ac00e9

2023-03-26 18:44 UTC, Secret-chest commented
What about a separate toggle for each button type?

2023-03-26 18:56 UTC, StioStudio commented
> What about a separate toggle for each button type?

Ummm.. I REALLY don't want to do that, but sure. It is a good idea.

2023-03-26 19:26 UTC, iqnite requested changes
The addon itself should work (didn't test right now), but why did you make a different CSS file for every button? Can't you combine many different items in one CSS declaration?

2023-03-26 19:26 UTC, iqnite commented on addons/compact-buttons/banner-button.css
> +}
Add a newline at the end of every file in order to make the Prettier checks succeed:
```suggestion
}

```

2023-03-26 19:26 UTC, iqnite commented on addons/compact-buttons/addon.json
> +    "enabledByDefault": false
Adding the ability to toggle the addon without having to reload the page would make the whole thing easier for many people:
```suggestion
    "enabledByDefault": false,
    "dynamicEnable": true,
    "dynamicDisable": true
```

2023-03-26 19:43 UTC, StioStudio commented
> The addon itself should work (didn't test right now), but why did you make a different CSS file for every button? Can't you combine many different items in one CSS declaration?

Because the file would be really long and so I have more overview over the CSS. And maybe because I forgot how to comments XD
I can fix it though :)

2023-03-26 20:00 UTC, BroJac5246 commented
> > The addon itself should work (didn't test right now), but why did you make a different CSS file for every button? Can't you combine many different items in one CSS declaration?
> 
> Because the file would be really long and so I have more overview over the CSS. And maybe because I forgot how to comments XD
> I can fix it though :)

CSS comments use the `/* */` format that JavaScript multi-line comments use. They can be single- or multi-line. [Source](https://www.w3schools.com/css/css_comments.asp)

2023-03-27 04:53 UTC, Secret-chest commented
If you use a separate file for each one, you can add settings

2023-04-07 11:23 UTC, StioStudio commented
Hey. I was wondering if this could be reviewed soon.

2023-04-07 18:28 UTC, StioStudio commented
Hi @WorldLanguages . Sorry for the ping but I was wondering if this could be reviewed/accepted soon.

2023-04-08 00:14 UTC, WorldLanguages commented
I believe there hasn't been enough discussion regarding how we'd decide which icons to use for buttons that don't have icons, such as share/unshare - and whether we want to offer that functionality in the first place.

2023-04-08 00:16 UTC, WorldLanguages commented
I also wonder how we would deal with the inconsistency of removing the words "see inside" from the project page, but keeping "see project page" on the editor. If we decide to let this addon handle both, this would set a weird precedent as the same addon would be changing UI in the website and editor at the same time 🤔

2023-04-08 00:16 UTC, WorldLanguages commented
I also would like to know if there's any specific reason the "compact buttons" concept is being restricted just to project pages? Couldn't it also be extended to profiles, studios, and other pages?

2023-04-08 01:15 UTC, Samq64 commented
> I also wonder how we would deal with the inconsistency of removing the words "see inside" from the project page, but keeping "see project page" on the editor.

I think that could be a toggle in #4018 along with #5866.

2023-04-08 06:43 UTC, StioStudio commented
> I believe there hasn't been enough discussion regarding how we'd decide which icons to use for buttons that don't have icons, such as share/unshare - and whether we want to offer that functionality in the first place.

I allready have made the icons and I have used the addon the last 2 weeks. They work pretty good allready (the ones I made)

2023-04-08 06:45 UTC, StioStudio commented
> I also wonder how we would deal with the inconsistency of removing the words "see inside" from the project page, but keeping "see project page" on the editor. If we decide to let this addon handle both, this would set a weird precedent as the same addon would be changing UI in the website and editor at the same time 🤔

I don't totaly understand this. The text goes away on editor and page. I don't see the problem.

2023-04-08 06:46 UTC, StioStudio commented
> I also would like to know if there's any specific reason the "compact buttons" concept is being restricted just to project pages? Couldn't it also be extended to profiles, studios, and other pages?

That is just because it is what I made. I was thinking to expand it to other things too.

2023-04-08 13:22 UTC, Secret-chest commented
I would really like a way to control each type of button separately.

2023-04-08 13:26 UTC, StioStudio commented
> I would really like a way to control each type of button separately.

Yeah. I need to learn SA settings first though

2023-04-08 14:50 UTC, BroJac5246 commented
> > I would really like a way to control each type of button separately.
> 
> Yeah. I need to learn SA settings first though

[addon.settings docs](https://scratchaddons.com/docs/reference/addon-api/addon.settings/)

2023-04-20 08:38 UTC, StioStudio commented
Don't mind the commits. It was just me doing it the wrong way

2023-04-22 13:08 UTC, TylerMS887 commented
Can I have a screenshot of this (or the Chrome extension file)?

2023-04-22 13:16 UTC, StioStudio commented
> Can I have a screenshot of this (or the Chrome extension file)?

What do you mean?

2023-04-22 14:06 UTC, TylerMS887 commented
> > Can I have a screenshot of this (or the Chrome extension file)?
> 
> What do you mean?

If you were talking about the screenshot, I want to see what this addon looks like. Click the image button on the top of the editor to upload a file to GitHub and insert it.
If you use Windows 11 Insider, open the Snipping Tool and select the modified parts.

If you were talking about the extension file, the Chrome extension file is a file that can be imported into Chromium based browsers in developer mode. In this case, the `packer.yml` file is missing so you will need to build yourself.

2023-04-22 14:53 UTC, StioStudio commented
![image](https://user-images.githubusercontent.com/98958235/233791709-f8fff639-1649-4c96-9d2e-702ab464fca5.png)
![image](https://user-images.githubusercontent.com/98958235/233791714-6efbb818-8574-4570-a540-07e46a7066e2.png)

2023-04-22 14:55 UTC, StioStudio commented
> > > Can I have a screenshot of this (or the Chrome extension file)?
> > 
> > 
> > What do you mean?
> 
> If you were talking about the screenshot, I want to see what this addon looks like. Click the image button on the top of the editor to upload a file to GitHub and insert it. If you use Windows 11 Insider, open the Snipping Tool and select the modified parts.
> 
> If you were talking about the extension file, the Chrome extension file is a file that can be imported into Chromium based browsers in developer mode. In this case, the `packer.yml` workflow file is missing from your fork so you will need to build yourself.

Does that work?

2023-06-05 09:47 UTC, closed without merging

2023-06-12 09:27 UTC, Secret-chest commented
Can it get settings for each button type? I want TurboWarp and Remix to not have icons but See inside and Share to have one.