Add "related addons" feature to settings page
ScratchAddons/ScratchAddons pull request #6104
Opened 2023-05-25 17:43 UTC by WorldLanguages

Resolves #5937

### Changes

- Addons can specify related addons in their manifests. In the exact same order, these addons are displayed as a pseudo-info box that provides links to the related addon(s).
- When clicking a related addon, the "related addons" modal is opened and is automatically scrolled to the addon that the user clicked. The clicked addon is also highlighted using the already existing addon-blink animation.
- Toggling addons and changing settings inside the modal works the same as searching the addons normally, and is kept in sync as expected. If the user clicks a related addon inside this view, the link opens in a new tab and only highlights the addon that the user clicked.
- This functionality is not available in the popup view of the settings page.

![brave_fVustW7hKO](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/9f7a43bc-8e25-42ae-8b07-a30e9e21a9f2)

2023-05-25 19:30 UTC, Samq64 commented
Here's a table with some addon relations World Languages and a couple other came up with on Discord. Feel free to edit it.
| addon 1                        |      | addon 2                      |                              |                        |
|--------------------------------|------|------------------------------|------------------------------|------------------------|
| dark-www                       | <--> | editor-dark-mode             |                              |                        |
| editor-dark-mode               | -->  | editor-theme3                |                              |                        |
| editor-stage-left              | <--> | editor-buttons-reverse-order |                              |                        |
| block-duplicate                | <--> | block-cherry-picking         |                              |                        |
| discuss-button                 | <--> | expanding-search-bar         |                              |                        |
| editor-theme3                  | <--> | custom-block-shape           |                              |                        |
| vol-slider                     | <--> | mute-project                 |                              |                        |
| editor-theme3                  | <--> | transparent-orphans          |                              |                        |
| better-emojis                  | <--> | emoji-picker                 |                              |                        |
| curator-link                   | <--> | more-links                   |                              |                        |
| scratchr2                      | <--> | horizontal-mystuff-tabs      |                              |                        |
| zebra-striping                 | <--> | editor-theme3                |                              |                        |
| share-through-mystuff          | <--> | editor-unshare-button        |                              |                        |
| scratch-messaging              | <--> | scratch-notifier             | msg-count-badge              |                        |
| fix-editor-comments            | <--> | editor-comment-previews      |                              |                        |
| scratchr2                      | <--> | old-studio-layout            |                              |                        |
| color-picker                   | <--> | 2d-color-picker              | default-costume-editor-color | pick-colors-from-stage |
| remove-search-bar-autocomplete | <--> | expanding-search-bar         |                              |                        |
| search-sprites                 | <--> | editor-searchable-dropdowns  | middle-click-popup           |                        |
| hide-stage                     | <--> | hide-flyout                  | tutorials-button             | sprite-properties      |
| remove-sprite-confirm          | <--> | hide-delete-button           |                              |                        |
| block-switching                | <--> | middle-click-popup           |                              |                        |
| old-studio-layout              | <--> | items-per-row                |                              |                        |
| old-studio-layout              | <--> | studio-followers             |                              |                        |
| items-per-row                  | <--> | custom-zoom                  |                              |                        |
| studio-tools                   | <--> | studio-followers             |                              |                        |
| expanded-backpack              | <--> | items-per-row                |                              |                        |
| block-count                    | <--> | project-info                 |                              |                        |
| data-category-tweaks-v2        | <--> | columns                      |                              |                        |
| live-featured-project          | <--> | feature-unshared             |                              |                        |
| feature-unshared               | <--> | remix-button                 | longer-wiwo                  |                        |
| confirm-actions                | <--> | remove-sprite-confirm        |                              |                        |
| move-to-top-bottom             | <--> | folders                      |                              |                        |
| youtube-fullscreen             | <--> | true-youtube-links           |                              |                        |
| full-signature                 | <--> | hide-signatures              |                              |                        |
| mediarecorder                  | <--> | blocks2image                 |                              |                        |

2023-05-25 19:53 UTC, WorldLanguages commented
There's some conversation in a different issue #6009 about grouping addons by more specific subcategories, such as "color picker" and "messages page".
We should ensure a majority of the related-addon relationships we add aren't just subcategories. For example, I'm not sure if color picker addons should be related to each other. They aren't directly related - they simply affect the same area of the editor.

2023-05-25 19:55 UTC, WorldLanguages commented
I would also suggest that we add the related-addon relationships as part of a different PR, after this one is merged.

@mxmou @lisa-wolfgang Any feedback about the implementation of the feature? (not the suggested relationships themselves)

2023-05-25 21:27 UTC, towerofnix commented
Yay, exciting!

Your second "resolves" link at the top of this PR may be broken, it links to itself 😅

2023-05-25 22:04 UTC, WorldLanguages commented
Reminder: I haven't tested whether clicking outside the "related addons" modal closes the modal or not. It should.

2023-05-25 22:10 UTC, DNin01 commented
> Reminder: I haven't tested whether clicking outside the "related addons" modal closes the modal or not. It should.

Clicking outside does close the modal.

2023-05-25 22:14 UTC, lisa-wolfgang commented
The implementation overall looks good to me.
Opening related addons from inside the related addons modal in a new tab seems a bit awkward, but it works well enough. One alternative would be to have a back button for the related addons window to allow for multiple layers of related addon navigation within the same tab, but I don't know if that would really be worth the effort.

2023-05-25 23:09 UTC, DNin01 commented
> The implementation overall looks good to me. Opening related addons from inside the related addons modal in a new tab seems a bit awkward, but it works well enough. One alternative would be to have a back button for the related addons window to allow for multiple layers of related addon navigation within the same tab, but I don't know if that would really be worth the effort.

Or, alternatively, just not display related addons from inside the modal.

2023-05-26 00:14 UTC, WorldLanguages commented
> Or, alternatively, just not display related addons from inside the modal.

I have considered that, but I thought that was worse.

> One alternative would be to have a back button for the related addons window to allow for multiple layers of related addon navigation within the same tab, but I don't know if that would really be worth the effort.

It's not worth the effort right now, I think.
IMO opening in a new tab is better than providing no way to go back, and that's the best we can do for now.

2023-05-27 16:14 UTC, WorldLanguages commented
@BroJac5246 Reason for the dislike emoji reaction?

2023-05-27 16:19 UTC, BroJac5246 commented
> @BroJac5246 Reason for the dislike emoji reaction?

I just don't really like this concept; I feel like we should find different methods of achieving the benefits of this. I'm somewhat _okay_ with it, but I don't exactly _like_ it.

2023-05-28 01:12 UTC, MaterArc commented
I kinda like the idea. I think it's a good way for people to search and find what they want to enable, it's a little bit overwhelming while looking at so many features anyways, so narrowing it down and picking out features that relate to the ones that the user already enabled is a good way to explore other addons that they might like.

2023-05-31 23:11 UTC, Racecar-Roaster commented
Like the fact that this can help find similar addons that people can also want in their scratch browser. I think this is helpful for someone who does animation on scratch. There can be similar tools to the colour HEX and I can find something also useful that I did not know I could use at all. And this can make the list of addons more organized and easier to find.

2023-07-11 15:00 UTC, iqnite requested changes
This change would resolve many concerns, but there's one thing I don't understand: Wouldn't it be more effective to scroll to the related addons, instead of opening them in a modal? The user could then jump back through the other addon's "Related" link.
For example: dark-www is related to dark-editor. So the user is viewing the dark-www addon and clicks on the dark-editor link in the "Related addons" section of the dark-www addon, which opens dark-editor. If the user wants to go back, they click on dark-www in the "Related addons" section of dark-editor.

2023-07-12 15:32 UTC, WorldLanguages commented
> Wouldn't it be more effective to scroll to the related addons, instead of opening them in a modal?

This has a few downsides:
1. For a good user experience we'd need to properly support the back button, which is not trivial
2. It's sometimes useful to see all of the related addons in the same list

Also, "related addon" relationships might not be bi-directional in some cases.

2023-08-18 00:58 UTC, DNin01 commented
60fps and turbowarp-player could probably be linked.

2025-01-05 01:21 UTC, WorldLanguages commented
@mxmou @samq64 I will resolve conflicts and try to get this merged this month

2025-01-05 21:22 UTC, WorldLanguages commented on webpages/settings/components/addon-body.html
> +  }
These CSS changes only apply some .addon-credits styles to .related-addons as well. There are no new rules.

2025-01-05 21:23 UTC, WorldLanguages commented on webpages/settings/components/addon-body.html
> +  .related-addons span:not(:first-child):not(:last-child)::after {
These CSS changes only apply some .addon-credits styles to .related-addons as well. There are no new rules.

2025-01-05 21:23 UTC, WorldLanguages commented on webpages/settings/components/addon-body.html
> +  }
This makes `Related addons:` bold.

2025-01-05 21:28 UTC, WorldLanguages commented on webpages/settings/components/addon-body.html
> +  }
Wrap is needed if the window is not wide enough to prevent the following unwanted layout:

![image](https://github.com/user-attachments/assets/a8d8fcc6-f826-47e8-b126-cecc540fe5b3)

2025-01-05 21:36 UTC, Samq64 commented
Right now the scrollbar extends into the header. Shouldn't it stop at the top of the scrollable content?

2025-01-05 21:42 UTC, WorldLanguages commented
> Right now the scrollbar extends into the header. Shouldn't it stop at the top of the scrollable content?

Thanks, I accidentally fixed that with my latest commit. I unnecessarily reinvented the wheel instead of copying the CSS layout of the existing More Settings modal.

2025-01-05 21:49 UTC, WorldLanguages commented on webpages/settings/components/modal.html
> +    max-width: 80%;
This also makes the More Settings modal a bit wider.

2025-01-05 21:49 UTC, WorldLanguages commented on webpages/settings/components/modal.html
> +    <div class="modal-content" v-click-outside="clickOutside" @click="closePickers">
This is necessary so that color pickers can be closed properly inside the modal

2025-01-05 22:06 UTC, WorldLanguages commented
This is how it looks now:

![image](https://github.com/user-attachments/assets/b35c2378-97e9-4c2d-a1e6-31959e3207ef)

![image](https://github.com/user-attachments/assets/31ba2ea8-71c8-4cc8-b8eb-fc8b04cb1a56)

![image](https://github.com/user-attachments/assets/7889250c-a8b2-4057-8a42-f53b63d3cc4d)

2025-01-05 22:09 UTC, WorldLanguages commented
@mxmou @DNin01 Maybe you could provide some feedback, do you think the screenshots I just sent look reasonable?

I'm thinking most addons might eventually get a "related addons" infobox assigned to them, that should mean we can't make it too distracting, or else it's equivalent to adding an info notice to virtually every addon.

2025-01-05 23:04 UTC, Samq64 commented
What about putting it at the bottom?
![image](https://github.com/user-attachments/assets/98a88e89-0169-469d-860f-913d101683cb)

2025-01-06 23:53 UTC, WorldLanguages commented
![image](https://github.com/user-attachments/assets/5787ed9b-9a33-4995-a5cb-a80659f82393)

2025-01-07 00:19 UTC, WorldLanguages commented on addons/custom-block-text/addon.json
> +  "relatedAddons": ["editor-theme3", "zebra-striping", "custom-block-shape"],
These are for testing, I will propose the actual ones in a followup PR 👍

2025-01-07 00:19 UTC, WorldLanguages commented on _locales/en/messages.json
> +    "message": "Related addons:"
Good point, right now I'm reusing the string for the modal title which is not ideal.

2025-01-07 00:24 UTC, Samq64 commented on _locales/en/messages.json
> +    "message": "Related addons:"
For the modal title it could be something like `Addons related to "{addon}"`?

2025-01-07 17:06 UTC, mxmou commented on _locales/en/messages.json
> +    "message": "Related addons:"
> For the modal title it could be something like `Addons related to "{addon}":`?

I think that's too long, especially if the addon has a long name. I suggest "Related addons:" for the label and "Related Addons" (title case) for the modal title.

2025-01-08 21:46 UTC, WorldLanguages commented on _locales/en/messages.json
> +    "message": "Related addons:"
@mxmou Good idea! Fixed

2025-01-09 10:50 UTC, mxmou commented
> If the user clicks a related addon inside this view, the link opens in a new tab and only highlights the addon that the user clicked.

This makes following a chain of "related addon" links - which I think is a reasonable thing to do - a very strange experience because the behavior of links alternates between opening a modal and opening a new tab. The simplest way to fix this is to remove the modal entirely and instead scroll to the related addon and highlight it. If the relations between addons are bidirectional, it will still be easy to go back to the previous addon.

Even if this problem was fixed in a different way, showing addons in a modal is quite weird with the current structure of the settings page. I'd prefer something like this:

![image](https://github.com/user-attachments/assets/ed44435d-4a72-4890-b713-037e1e1db995)

2025-01-09 10:55 UTC, mxmou commented
> What about putting it at the bottom? ![image](https://private-user-images.githubusercontent.com/81489795/400256840-98a88e89-0169-469d-860f-913d101683cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MTkxODQsIm5iZiI6MTczNjQxODg4NCwicGF0aCI6Ii84MTQ4OTc5NS80MDAyNTY4NDAtOThhODhlODktMDE2OS00NjlkLTg2MGYtOTEzZDEwMTY4M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDEwMzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOTdhNzgxZGVjOWE0MWVlNWI2NGUyMTdjODZhYjc5YmM2OGNiMGExNjliZTM2YmQ0M2M5NjgxZDdiNmE4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vj04Ij39tXM7JcV4i6xXuVJ-Ph6c0a4qGlMhV8L1sWo)

Placing it at the bottom is a good idea but I think it should look like this screenshot, without a background. A better way to make it stand out a bit is to use a larger font size (14px) and a brighter text color (`--content-text` instead of `--description-text`).

2025-01-09 18:22 UTC, WorldLanguages commented
> Even if this problem was fixed in a different way, showing addons in a modal is quite weird with the current structure of the settings page. I'd prefer something like this:
> 
> ![image](https://private-user-images.githubusercontent.com/51849865/401508161-ed44435d-4a72-4890-b713-037e1e1db995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NDY5MTQsIm5iZiI6MTczNjQ0NjYxNCwicGF0aCI6Ii81MTg0OTg2NS80MDE1MDgxNjEtZWQ0NDQzNWQtNGE3Mi00ODkwLWI3MTMtMDM3ZTFlMWRiOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE4MTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYzY1M2U2NzQ0ZDMwNWNjNDgyZGRhMDIyOGY5ZWFlMTNlMmExY2JmNDM3MDFkMjk3YzAxOGNkODU1NjljYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5aTpAn3VlicnylI13MAxjpU50MyDmV7zxELeXlfYYlI)

That looks nice!
I would assume the value of the search bar, as well as any applied sidebar filters, would be ignored when on this view. That's some weirdness that we can ignore if we go for a modal (but by itself doesn't justify a modal being a superior choice)

2025-01-09 18:30 UTC, WorldLanguages commented
> This makes following a chain of "related addon" links - which I think is a reasonable thing to do - a very strange experience because the behavior of links alternates between opening a modal and opening a new tab. The simplest way to fix this is to remove the modal entirely and instead scroll to the related addon and highlight it.

There's some added complexity if we want to do that, for example we should think whether we want to clear the user's search and filters in order to scroll to the related addon, in cases where it's not already on the list.

Another approach we can consider, is to keep all of the Related Addons experience inside the same modal. It would be equivalent to stacking multiple modals one above the other, but the ones that get behind the new modal get lost.

2025-01-09 18:45 UTC, Samq64 commented
If the modal is kept, a back button could be added.

2025-01-14 09:44 UTC, mxmou commented
> If the user doesn't see the back arrow for some reason, I wonder if they'll try to go back by clicking the All button on the sidebar. Kinda tricky to decide what that button should do in this situation.

I think clicking any sidebar item should exit the related addons view and switch to that category.

> That looks nice!
> I would assume the value of the search bar, as well as any applied sidebar filters, would be ignored when on this view. That's some weirdness that we can ignore if we go for a modal (but by itself doesn't justify a modal being a superior choice)

There should probably be a visual indication of this, for example making all items in the sidebar appear unselected.

Another thing to consider is that users might want to search for something while on this view. One solution is to exit it automatically when the value of the search bar is changed. Another option is to hide the search bar when viewing related addons - with the current position of the search bar that would be quite weird, but we could do something like this:

![related_addons_mockup_1.jpeg](https://github.com/user-attachments/assets/202d0215-ca7f-423a-a9e1-ef601c9442f7)

![related_addons_mockup_2.jpeg](https://github.com/user-attachments/assets/33a714dc-8153-49e6-b206-a2318e82d138)

This would use more vertical space than the current layout with the search bar in the header, but it has another advantage: putting the search bar next to the name of the selected category might make it clearer that it will only search in that category. It also makes the selected category visible if the sidebar is closed. Unfortunately, it makes the search bar "hidden" in the corner, but it could be highlighted when focused to make it more noticeable (because it gets focus automatically when the page loads):

![related_addons_mockup_3.png](https://github.com/user-attachments/assets/c8ff9e9d-1301-4543-af66-dfddeeca22f1)

2025-01-24 21:37 UTC, WorldLanguages commented
Anyone want to take over?

2025-03-24 13:51 UTC, Samq64 commented
This now works looks similar to mxmou's screenshots. There is no navigation tracking yet though so the back button exits the related addons view entirely and doesn't scroll to the originally clicked addon.

2025-03-24 20:33 UTC, Samq64 commented
https://github.com/ScratchAddons/ScratchAddons/pull/6104/commits/322b460dc79d264fcd8b57fc15875e088af687c3 changed the 2 instances of `.addons-container.placeholder` to `.addons-container .placeholder` in `/webpages/settings/style.css` but GitHub doesn't like the fact that it's a white space only change.

2025-03-24 21:03 UTC, Samq64 commented
The implementation isn't perfect but it works well apart from a race condition with the header text.

https://github.com/user-attachments/assets/b8de1d37-1118-44f1-ae30-55291caa214a

2025-03-25 12:43 UTC, Samq64 commented
This was also a bug in the modal version but when clicking a related addon from the themes category all related addons also have the theme tag.

Adding a check in the `addon-tag.js` had a huge performance hit, so it's not fixed yet.

2025-04-02 16:36 UTC, Samq64 commented
What should be done about performance? Currently navigating away from the related view causes the addon list to be reloaded without the placeholder.

2025-04-02 17:09 UTC, WorldLanguages commented
By placeholder do you mean the "loading indicators"? I think it's fine to only show them on first load.

The usefulness of listing "related addons" wins over any performance concerns.

2025-04-03 08:07 UTC, mxmou reviewed
I don't like the way the list of related addons is styled - see https://github.com/ScratchAddons/ScratchAddons/pull/6104#issuecomment-2579833331.

2025-04-03 08:07 UTC, mxmou commented on webpages/settings/style.css
> +  font-size: 16px;
```suggestion
  font-size: 16px;
  font-weight: 500;
```

2025-04-04 07:33 UTC, mxmou approved these changes
Now that the name of the selected category is shown in the toolbar, it would make sense to put the button that opens the sidebar in small mode next to it. I can do that in a future PR.

2025-04-04 07:33 UTC, mxmou commented on webpages/settings/components/addon-body.js
>            // Do not extend when enabling in popup mode, unless addon has warnings
```suggestion
          // Do not extend when enabling in popup mode, unless addon has warnings
          // Do not collapse when disabling in related addons view
```

2025-04-04 07:33 UTC, mxmou commented on webpages/styles/components/search.css
> +  border: 1px solid transparent; /* prevent layout shift */
```suggestion
  border: 1px solid transparent; /* prevent layout shift when focused */
```

2025-04-05 12:57 UTC, iqnite approved these changes
The implementation is good, but would merging this PR really "close" the issues? What about the addons listed in https://github.com/ScratchAddons/ScratchAddons/pull/6104#issuecomment-1563406851?

Also, the addon manifest validation workflow should be updated to not mark the "related addons" feature as incorrect.

2025-04-05 13:04 UTC, Samq64 commented
https://github.com/ScratchAddons/ScratchAddons/pull/6104#discussion_r1904767014:

> These are for testing, I will propose the actual ones in a followup PR 👍

2025-04-22 15:15 UTC, WorldLanguages commented
The search bar on the right edge feels a bit weird to me.
Will new users find it easily?

2025-04-22 15:22 UTC, WorldLanguages commented
Other than that, I would like to say the back-button implementation is excellent.

2025-04-22 16:51 UTC, Samq64 commented
> Will new users find it easily? (I see that a focus color was added, but I'm not sure if that's enough)

I considered using the same focus styles as other inputs but thought it was too distracting in the popup. What do you think?

2025-04-23 00:33 UTC, Samq64 commented
I've pushed the suggested style changes.

One more minor thing: currently the related header is displayed as `Related to Addon name` keeping the name sentence case. Would one of these be better?
- `Related to addon name` (lowercase)
- `Related to: Addon name`
- `Related to "Addon name"`

2025-04-23 06:14 UTC, mxmou commented
> I've pushed the suggested style changes.
> 
> One more minor thing: currently the related header is displayed as `Related to Addon name` keeping the name sentence case. Would one of these be better?
> - `Related to addon name` (lowercase)
> - `Related to: Addon name`
> - `Related to "Addon name"`

I think `Related to: Addon name` is the most translation-friendly.

2025-05-17 22:36 UTC, WorldLanguages commented
@mxmou @Samq64 Good to merge?

2025-05-18 12:23 UTC, merged