Use purple everywhere on the forums
ScratchAddons/ScratchAddons pull request #6479
Opened 2023-08-02 20:11 UTC by Samq64

Resolves #6296

### Changes

Updates addons to use purple everywhere on the forums instead of `#28a5da`.

### Reason for changes

Scratch has updates the forums to use purple to match the rest of the site and addons would look out of place if they weren't updated to use the new colours.

### Tests

Tested on the forums on Chromium 115.

2023-08-03 05:47 UTC, mxmou requested changes

2023-08-03 05:47 UTC, mxmou commented on addons/dark-www/addon.json
> -    },
This (and the CSS that uses it) should stay - it's for the blue preset.

2023-08-03 05:47 UTC, mxmou commented on addons/op-badge/forums.css
> +  background-color: var(--darkWww-button, #855cd6);
Only the default value needs to be updated here.

```suggestion
  background-color: var(--darkWww-button-scratchr2PostHeader, #855cd6);
```

2023-08-03 06:27 UTC, Secret-chest commented
Please, make the forums header customisable! I hate ocular green and purple!

2023-08-03 12:46 UTC, Samq64 commented
> Please, make the forums header customisable! I hate ocular green and purple!

You don't have to use purple but changing the green to something else isn't in the scope of the PR.

2023-08-03 12:58 UTC, mxmou commented on addons/dark-www/addon.json
> -          "#4d97ffff": "#28a5da",
Removing this breaks the "Scratch's default colors (blue)" preset:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/3607e9c2-33e1-41aa-b24f-387e5d099698)

It should look the same as the 2.0 presets:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/ef19b3d1-5ddc-47cc-8289-6380c276a910)

2023-08-04 13:58 UTC, mxmou approved these changes

2023-08-04 13:58 UTC, mxmou commented on addons/forum-quote-code-beautifier/addon.json
> +      "default": "#855cd6",
There should probably be a setting migration for existing users.

2023-08-05 15:25 UTC, WorldLanguages commented
Self note: this PR does not change any translation strings

2023-08-11 14:52 UTC, WorldLanguages commented on background/get-addon-settings.js
> +        }
I think this will continuously force the user to return to the previous setting if they come back to the old color.

2023-08-11 14:59 UTC, WorldLanguages approved these changes

2023-08-15 15:29 UTC, merged