Fix site nav buttons visible under expanding search bar with scratchr…
ScratchAddons/ScratchAddons pull request #6569
Opened 2023-08-20 18:52 UTC by DNin01

…2 enabled

### Changes

Sets the opacity of the navigation bar links to 0 to avoid them showing up on top of (technically, under) the search bar while the `scratchr2` addon is enabled.

### Reason for changes

To fix #6567

### Tests

Tested in Edge 115.

2023-08-20 19:11 UTC, WorldLanguages commented
How sure are you about this fix? Reverting to the previous code is also a possibility. (we really need to test a bit more - both www and 2.0 pages with other addons enabled and disabled)

2023-08-20 19:25 UTC, DNin01 commented
> How sure are you about this fix? Reverting to the previous code is also a possibility. (we really need to test a bit more - both www and 2.0 pages with other addons enabled and disabled)

There's probably still some testing that could be done.

2023-08-21 10:50 UTC, mxmou requested changes
It's still possible to click on the first hidden link. Using `overflow: hidden` instead of `opacity: 0` would fix that.

2023-08-21 21:39 UTC, WorldLanguages commented
We can release v1.34.0 after fixing this, by either 1) reverting the bad commit or 2) merging this with some good testing.

2023-08-21 21:40 UTC, WorldLanguages commented
Ping me if you want to merge some `colorblind` addon PRs for v1.34.1 too. As long as they're approved by DNin01 (the addon author).

2023-08-21 22:06 UTC, DNin01 commented
> We can release v1.34.0 after fixing this, by either 1) reverting the bad commit or 2) merging this with some good testing.

Did you mean v1.34.1?

2023-08-21 22:08 UTC, WorldLanguages commented
Yeah

2023-08-22 18:32 UTC, mxmou approved these changes

2023-08-22 18:51 UTC, WorldLanguages commented
Good to go then, let's hope there are no remaining bugs lol.

Will release in a few hours. Please test!

2023-08-23 00:13 UTC, merged

2023-08-25 17:19 UTC, WorldLanguages commented
https://scratch.mit.edu/discuss/topic/706469/

Is this somehow related to this addon?

> Recently some Google users have reported that when typing their username into the Scratch search bar (3.0), their login details show up (as shown in this project: https://scratch.mit.edu/projects/885547573.

2023-08-25 17:32 UTC, mxmou commented
> https://scratch.mit.edu/discuss/topic/706469/
> 
> Is this somehow related to this addon?
> 
> > Recently some Google users have reported that when typing their username into the Scratch search bar (3.0), their login details show up (as shown in this project: https://scratch.mit.edu/projects/885547573.

I can reproduce the bug on Chrome with SA disabled.

2023-08-25 19:44 UTC, medlans commented
> https://scratch.mit.edu/discuss/topic/706469/
> 
> Is this somehow related to this addon?
> 
> > Recently some Google users have reported that when typing their username into the Scratch search bar (3.0), their login details show up (as shown in this project: https://scratch.mit.edu/projects/885547573.

No, I can replicate but only in incognito mode (and when I enabled incognito mode, all my extensions were disabled so I had no scratch-www -> scratchr2 or Scratch Addons)

2023-08-25 19:52 UTC, DNin01 commented
> https://scratch.mit.edu/discuss/topic/706469/
> 
> Is this somehow related to this addon?
> 
> > Recently some Google users have reported that when typing their username into the Scratch search bar (3.0), their login details show up (as shown in this project: https://scratch.mit.edu/projects/885547573.

Does `remove-search-bar-autocomplete` fix that?

2023-08-26 03:16 UTC, BroJac5246 commented
> > https://scratch.mit.edu/discuss/topic/706469/
> > 
> > Is this somehow related to this addon?
> > 
> > > Recently some Google users have reported that when typing their username into the Scratch search bar (3.0), their login details show up (as shown in this project: https://scratch.mit.edu/projects/885547573.
> 
> Does `remove-search-bar-autocomplete` fix that?

Unfortunately not. This happened to me on Chrome 114 on a Chromebook with `remove-search-bar-autocomplete` enabled.

This could be added to the addon, though, if it can be fixed and the ST doesn't fix it.

2023-08-26 03:21 UTC, DNin01 commented
> This could be added to the addon, though, if it can be fixed and the ST doesn't fix it.

I would be surprised if it isn't fixed in a few weeks.