`cloud-games`: Add character limit to `url` setting in table
ScratchAddons/ScratchAddons pull request #6775
Opened 2023-10-15 01:05 UTC by DNin01

### Changes

Adds a character limit of 44 characters to the URL string fields in the Cloud games addon. AFAIK, 44 characters is the most you'll ever need:
```
https://               =  8
scratch.mit.edu/  + 16 = 24
projects/         +  9 = 33
1234567890/       + 11 = 44
```

### Reason for changes

I don't know why, it just seems like a good precaution nonetheless.

### Tests

Tested.

2023-10-15 08:02 UTC, mxmou requested changes
Many project and studio URLs accepted by the addon are longer than that:
* https://scratch.mit.edu/projects/905650648/#comments-360987454 (62 characters)
* https://scratch.mit.edu/studios/33858471/curators (49 characters)
* https://scratch.mit.edu/studios/33858471/comments#comments-237564077 (68 characters)

If a limit is added, it should be longer than the expected length of a URL - maybe 100 characters.

2023-10-15 14:49 UTC, WorldLanguages commented on addons/cloud-games/addon.json
> +          "max": 44,
```suggestion
          "max": 100,
```

2023-10-15 15:44 UTC, Secret-chest commented
Also, let's not forget we're soon getting to 10-digit project IDs

2023-10-15 16:04 UTC, mxmou commented
> Also, let's not forget we're soon getting to 10-digit project IDs

The example link in the OP has a 10-digit ID.

2023-10-15 16:29 UTC, DNin01 commented on addons/cloud-games/addon.json
> +          "max": 44,
100 is the default limit.

2023-10-15 16:32 UTC, DNin01 commented
> Many project and studio URLs accepted by the addon are longer than that:
> 
> * https://scratch.mit.edu/projects/905650648/#comments-360987454 (62 characters)
> * https://scratch.mit.edu/studios/33858471/curators (49 characters)
> * https://scratch.mit.edu/studios/33858471/comments#comments-237564077 (68 characters)
> 
> 
> 
> If a limit is added, it should be longer than the expected length of a URL - maybe 100 characters.

Just because certain URLs are accepted doesn't mean they're expected/intended to be. Such URLs would be cut off anyway and would still technically work cut off.

2023-10-15 22:12 UTC, WorldLanguages commented on addons/cloud-games/addon.json
> +          "max": 44,
Oh

2023-10-15 22:13 UTC, WorldLanguages commented
Well, it's true that the URLs would also work cut-off.

2023-10-16 05:56 UTC, closed without merging

2023-10-16 05:56 UTC, apple502j commented
Hey, let's add limits to settings it will be fine (says a person whose very commit was reversed for this)

2023-10-16 14:59 UTC, WorldLanguages commented
@apple502j Which commit are you referring to?

2023-10-16 18:48 UTC, DNin01 commented
> @apple502j Which commit are you referring to?

#6744.

2023-10-17 01:52 UTC, DNin01 commented
Realistically, though, I don't imagine anyone is going to _actually want_ to input a URL longer than 44 characters - the worst-case scenario for direct project page URLs with up to 10 ID digits (when it reaches a billion) as I described above. No one's losing anything by being limited to 44 characters here.

From my testing, longer values are cut off and still work, which means that if a longer URL was accidentally pasted, it would be truncated, saving storage space. That's the only realistic advantage I can think of.

2023-10-19 01:55 UTC, DNin01 commented
An alternative to this would be parsing the value in the input field to omit `https://scratch.mit.edu/` and anything after the ID.

[https://scratch.mit.edu/<b>projects/905650648</b>/#comments-360987454](https://scratch.mit.edu/projects/905650648/#comments-360987454)

That would save much more space! Just limiting the length like this doesn't help at all the vast majority of the time.