`scratchr2`: Style comment warnings correctly
ScratchAddons/ScratchAddons pull request #6873
Opened 2023-11-15 16:40 UTC by mybearworld

Resolves #6859

### Changes

Styles comment warnings on profiles so they look as they do in scratchr2. This also makes the issue linked above no longer apply.

![An empty comment with a warning saying "You can't post an empty comment!" on a scratchr2 page with the scratchr2 addon enabled, with the warning looking just as with scratch-www.](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/21743a3a-2f53-4c6f-9ee5-bc3d5ad75709)

### Reason for changes

Making it more consistent, and fixing a bug.

### Tests

Tested in Edge.

2023-11-15 20:44 UTC, mybearworld commented
Just realized this probably won't affect replies.

2023-11-16 15:28 UTC, mybearworld commented
> Just realized this probably won't affect replies.

Fixed:

![An empty reply with a warning saying "You can't post an empty comment!" on a scratchr2 page with the scratchr2 addon enabled, with the warning looking just as with scratch-www.](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/7d5af214-4e03-4bd4-8982-fab674af3b71)

2023-11-25 16:04 UTC, mxmou requested changes
The error text is currently larger than in scratch-www. I think it should be the same size as the comment text:
```css
#comments form .tooltip .hovertext .text {
  font-size: 13px;
}
```

2023-11-25 16:04 UTC, mxmou commented on addons/scratchr2/scratchr2_comments.css
> +  margin-bottom: 0.5rem;
```suggestion
  margin-bottom: 8px;
```

`1rem` on scratchr2 pages isn't the same size as in scratch-www.

2023-11-25 16:04 UTC, mxmou commented on addons/scratchr2/scratchr2_comments.css
> +  margin-bottom: 0.5rem;
```suggestion
  margin-bottom: 8px;
```

2023-11-25 16:04 UTC, mxmou commented on addons/scratchr2/scratchr2_comments.css
> +  padding: 0.25rem;
```suggestion
  padding: 4px;
```

2023-12-05 18:43 UTC, mxmou commented
The font size is still too large. Everything else looks good.

2023-12-15 19:33 UTC, WorldLanguages commented
@mybearworld Any reasons not to set the font size to 13px, as mxmou suggested?

2023-12-15 19:43 UTC, mybearworld commented
Sorry, I missed it - done

![Font size adjusted](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/54c78df3-7d11-4513-92fb-d425dfcbd6ca)

2023-12-16 07:47 UTC, mxmou approved these changes

2023-12-17 19:56 UTC, Samq64 approved these changes

2023-12-17 20:13 UTC, merged