discuss-button: hide username using CSS
ScratchAddons/ScratchAddons pull request #6889
Opened 2023-11-25 15:45 UTC by mxmou

Resolves #6880

### Changes

Uses CSS instead of JavaScript to hide the username when the "compact user dropdown" setting is enabled.

### Reason for changes

To fix a race condition and make the code simpler.

### Tests

Tested on Edge and Firefox.

2023-11-25 19:01 UTC, DNin01 requested changes
Great to see there's a way to do that with CSS! Even setting a minimum font size in the browser doesn't override it (because it's 0, I guess?).

However, the `scratchr2` addon overrides this on scratchr2 pages. This could be fixed by using `!important`, ordering this addon after `scratchr2` in `addons.json`, or increasing the specificity.

2023-11-25 19:49 UTC, DNin01 approved these changes

2023-11-26 15:34 UTC, WorldLanguages approved these changes

2023-11-26 15:35 UTC, WorldLanguages commented
Thanks DNin01 for noticing the conflict with the scratchr2 addon

2023-11-26 15:35 UTC, merged