Style WebGL modal with `editor-dark-mode`
ScratchAddons/ScratchAddons pull request #7038
Opened 2024-01-03 17:45 UTC by mybearworld

Resolves #7073

### Changes

Add the classes from the WebGL not supported modal to some preexisting rules.

![The WebGL modal in dark mode](https://i.ibb.co/5rRW633/yay.png)

### Reason for changes

Consistency.

### Tests

Tested in Edge.

2024-01-03 19:27 UTC, Samq64 approved these changes
Tested on Firefox

2024-01-05 08:59 UTC, mxmou requested changes

2024-01-05 08:59 UTC, mxmou commented on addons/editor-dark-mode/experimental_editor.css
> +[class*="webgl-modal_button-row"] > button,
The border color also needs to be set. It currently looks like this with the TurboWarp Dark preset:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/7fef9bb3-f0bc-457c-9004-4c682c1851fb)

2024-02-17 16:03 UTC, mxmou approved these changes

2024-02-18 17:11 UTC, merged