new Auto-hiding block palette option
ScratchAddons/ScratchAddons pull request #7076
Opened 2024-01-13 16:22 UTC by callumjt

adds a new option to Auto-hiding block palette which makes the flyout lock when the page is loaded 

tested on chrome and firefox :)

(sorry for low framerate, for some reason obs decided to die)

https://github.com/ScratchAddons/ScratchAddons/assets/116295240/e93ebaf6-017d-46e5-8193-a5f20e165a07

2024-01-13 16:24 UTC, CubesterYT commented
I remember this was asked for in TurboWarp, I'm so stoked this is coming, I need it bad.

2024-01-13 16:27 UTC, LilyMakesThings commented
A dream come true, hope to see this in TurboWarp ASAP <3

2024-01-13 19:58 UTC, DNin01 requested changes
Pretty cool, but this does need testing with the "Category click" setting. There's no lock button when you use that setting, but it could instead be programmed to start out open, requiring a category click to close. Related: #5821. What actually happens in this PR is **you can't close it**.

I like to set this addon to toggle on category click and I've always wanted it to start out open.

2024-01-13 20:32 UTC, callumjt commented
> Pretty cool, but this does need testing with the "Category click" setting. There's no lock button when you use that setting, but it could instead be programmed to start out open, requiring a category click to close. Related: #5821. What actually happens in this PR is **you can't close it**.
> 
> I like to set this addon to toggle on category click and I've always wanted it to start out open.

was making this and tried to set "motion" to enabled on game start but "Blockly.getMainWorkspace().getToolbox().selectedItem_.setSelected(false);" doesnt seem to work

2024-01-13 22:16 UTC, DNin01 commented
@mxmou, do you want to take a look?

2024-01-13 22:27 UTC, callumjt commented
the code i used is 

`const option = addon.settings.get("lockLoad");
    if (option) {
      if (getToggleSetting() === "category") {
        Blockly.getMainWorkspace().getToolbox().selectedItem_.setSelected(true);
        onmouseleave(null, 0);
        toggle = true;
      } else {
        flyoutLock = option;
        updateLockDisplay()
      }
      flyOut.classList.remove("sa-flyoutClose");
      scrollBar.classList.remove("sa-flyoutClose");
    };`

2024-01-14 07:42 UTC, mxmou commented
> was making this and tried to set "motion" to enabled on page load but "Blockly.getMainWorkspace().getToolbox().selectedItem_.setSelected(true);" doesnt seem to work

That's because of the `setSelected(false)` call on line 191. Try adding `&& !toggle` to the `if (!shouldScroll)` condition. You can then remove line 53.

2024-01-14 21:14 UTC, DNin01 approved these changes
Seems to be working!

Only thing is the block category [doesn't initially appear highlighted](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/6b86a6a9-0c81-4dc1-81e9-e82adb1c2eb1) if you've scrolled the block palette to the very top and then dynamically enable the addon using the "Category click" and "Lock by default" settings, but that's very minor.

2024-01-19 14:09 UTC, Samq64 reviewed
Could `latestUpdate` be added to highlight the new setting?

2024-01-19 14:09 UTC, Samq64 commented on addons/hide-flyout/addon.json
> +      "name": "Lock by default",
The category click setting doesn't have a lock.
```suggestion
      "name": "Open by default",
```

2024-01-20 11:04 UTC, callumjt commented
Changed the option name and added latestUpdate

2024-01-20 13:15 UTC, Samq64 commented on addons/hide-flyout/addon.json
> +  "latestUpdate": "1.36.0",
```suggestion
  "latestUpdate": {
    "version": "1.36.0",
    "newSettings": ["lockLoad"]
  }.
```

2024-01-20 14:34 UTC, Samq64 approved these changes

2024-01-20 17:24 UTC, mxmou requested changes
Lines 151-155 (in the `"reenabled"` event listener) close the palette if the addon is dynamically enabled and the mode is category click. This should only happen if the new setting is disabled.

When switching from category click to a different mode, the palette should be automatically locked if the new setting is enabled.

2024-01-20 17:24 UTC, mxmou commented on addons/hide-flyout/userscript.js
> +        onmouseleave(null, 0);
```suggestion
```
`onmouseleave()` closes the palette. There's no reason to call it here.

2024-01-23 11:10 UTC, mxmou approved these changes

2024-01-23 15:49 UTC, merged