Setings page header adjustments
ScratchAddons/ScratchAddons pull request #7485
Opened 2024-06-01 00:18 UTC by Samq64

Resolves #

### Changes

Removes the white space from `icon-transparent.svg` and makes it appear bigger in header, but not as big as #5104. The button hover from #7333 has also been added to the logo on the license and permission pages.

### Reason for changes

The hover is nice since it's otherwise not obvious the logo is clickable and the SVG white space only exists because I was lazy in #4810.

### Tests

Tested in Chromium and Firefox. RTL also seems fine.

2024-06-01 09:04 UTC, Waakul commented
I would recommend that you provide screenshots

2024-06-01 13:08 UTC, Samq64 commented
| Before | After |
|-----|-----|
|![popup-old](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/845d0f0d-b8b1-468a-85f9-4fbf497e2117) | ![popup-new](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/c5433af7-20e3-49ff-b890-6a6ec345127f) |
| ![settings-old](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/e290401e-08b8-471a-86b0-7ac12506d786) | ![settings-new](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/e15cb7ff-3ead-4d35-87a8-33d6cc2df93e)
| ![settings-small-old](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/b9d42251-0dcd-4707-a679-8fc62790a850) | ![settings-small-new](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/077a4c56-c4c8-40d3-9840-01e9ac7af3e6)
| ![other-pages-old](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/0f0e9590-2d0c-40fe-af41-110659dee2c0) | ![other-pages-new](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/8cc12356-ca54-4bcd-a615-637118178bda) |

2024-06-01 18:13 UTC, DNin01 reviewed
For the pages, I like how the logo is bigger, but I did like the slightly more space between the text, the logo, and the beginning/left edge of the page from before.

I do like how it looks on the popup after this change, though!

2024-06-01 18:33 UTC, mxmou requested changes

2024-06-01 18:40 UTC, Samq64 commented on webpages/settings/index.html
> +      <img :src="switchPath" class="header-button" @click="sidebarToggle()" v-cloak v-show="smallMode" alt="Logo" />
If the styles aren't necessary could it be changed to an ID?

2024-06-01 18:42 UTC, Samq64 commented
> For the pages, I like how the logo is bigger, but I did like the slightly more space between the text, the logo, and the beginning/left edge of the page from before.

That's a side effect of the image not being square anymore.

2024-06-09 16:07 UTC, mxmou requested changes
Bug: the icon isn't centered on the Licenses page. This is easiest to see when hovered:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/e0d4c567-8833-40c2-b46c-e415a34233ce)
It could be fixed by adding either `display: flex` or `line-height: 0` to the `<a>` element.

The spacing on the settings page is now better, but I think it should be the same as in the popup (20px on both sides). Ideally, the spacing on the Licenses page would also be the same (`padding: 17.5px 20px` and no margin).

2024-06-09 20:28 UTC, Samq64 commented
The logo on the permission page is also a link. Does that make sense to keep?

2024-06-10 07:00 UTC, mxmou commented
> The logo on the permission page is also a link. Does that make sense to keep?

It's not very useful, but I don't think it needs to be removed.

2024-06-10 09:47 UTC, mxmou approved these changes

2024-07-31 18:42 UTC, WorldLanguages commented
@Samq64 No screenshots?

2024-08-01 00:52 UTC, Samq64 commented
https://github.com/ScratchAddons/ScratchAddons/pull/7485#issuecomment-2143444073

Things changed a little after Mxmou's suggestions

2024-08-02 19:04 UTC, WorldLanguages commented
Okay, you both are org members so I'm merging this,

2024-08-02 19:04 UTC, merged