Rework display none while disabled
ScratchAddons/ScratchAddons pull request #7559
Opened 2024-06-20 03:57 UTC by TheColaber

Extends #4924

Changes Tab.displayNoneWhileDisabled to create a style element on the page that has a display: none !important when the addon is disabled.

Hopefully this can get merged before any new addons uses the api...

2024-06-21 19:17 UTC, mxmou requested changes

2024-06-21 19:17 UTC, mxmou commented on addons/one-click-studio-invites/userscript.js
> +    addon.tab.displayNoneWhileDisabled(button);
Same as above, but with `display: block`.

2024-06-21 19:17 UTC, mxmou commented on addons/vol-slider/userscript.js
> +  addon.tab.displayNoneWhileDisabled(container);
Same

2024-06-21 19:42 UTC, TheColaber commented on addons/emoji-picker/userscript.js
> +    addon.tab.displayNoneWhileDisabled(emojiButton);
i tested this addon, and all the ones you mentioned below, and they seemed to work without adding any extra styles

2024-06-21 19:49 UTC, mxmou commented on addons/emoji-picker/userscript.js
> +    addon.tab.displayNoneWhileDisabled(emojiButton);
They work but the layout is slightly broken - for example, the volume slider isn't centered. Compare them with the stable version.

2024-06-22 05:58 UTC, mxmou commented on addons/emoji-picker/userstyle.css
> +  display: inline-block;
`.sa-emoji-button-container` also needs this style. It currently looks like this in this PR:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/122a1666-8dd6-4205-9f56-995459826cf6)

On master:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/c41022f6-51bd-45cf-8ff4-f382fa19a36b)

2024-06-22 15:05 UTC, mxmou approved these changes

2024-07-23 19:42 UTC, Samq64 approved these changes

2024-07-24 22:26 UTC, TheColaber commented
Updated new addon. Good to go.

2024-07-24 22:26 UTC, merged