Add transition code for workspace-dots
ScratchAddons/ScratchAddons pull request #7573
Opened 2024-06-22 16:38 UTC by TheColaber

2024-06-22 17:05 UTC, Samq64 commented on background/get-addon-settings.js
> +      delete addonSettings["editor-dark-mode"]["dots"];
Very minor but deleting the old setting should probably be last in case something errors out. Also settings without dashes can just use dot notation.

2024-06-23 16:19 UTC, WorldLanguages commented on background/get-addon-settings.js
> +    if (addonsEnabled["editor-dark-mode"] && addonSettings["editor-dark-mode"]["dots"] === false) {
Did you mean true instead of false?

2024-06-23 16:20 UTC, TheColaber commented on background/get-addon-settings.js
> +    if (addonsEnabled["editor-dark-mode"] && addonSettings["editor-dark-mode"]["dots"] === false) {
no

2024-06-24 15:04 UTC, mxmou requested changes

2024-06-24 15:04 UTC, mxmou commented on background/get-addon-settings.js
> +      addonSettings["workspace-dots"]["theme"] = "none";
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/c5e40424-5f85-42cc-89dc-8ab6d5c2dc36)

2024-06-25 13:42 UTC, mxmou approved these changes

2024-06-25 18:58 UTC, Samq64 approved these changes

2024-07-06 23:36 UTC, WorldLanguages commented
Our many lines of transition code are getting messy and inconsistent, but it's not too bad.

2024-07-06 23:37 UTC, merged