Improve efficiency in `copy-message-link` on profiles
ScratchAddons/ScratchAddons pull request #7657
Opened 2024-07-17 23:07 UTC by rgantzos

Resolves #7656 

### Changes

Used `markAsSeen` and added a new class to comments that have already had the button added. This ensures that comments don't get used twice and also improves efficiency by not having the waitForElement API read over the comment again.

### Reason for changes

Lag can become pretty noticeable on profiles (as the project/studio one worked differently) when you have a lot of comments on the page.

### Tests

macOS Sonoma 14.5
Chrome Version 126.0.6478.36 (Official Build) beta (arm64)

2024-07-18 00:51 UTC, Samq64 commented on addons/copy-message-link/profile.js
>    let pass = 0;
```suggestion
```

2024-07-18 14:52 UTC, Samq64 approved these changes

2024-07-18 16:19 UTC, WorldLanguages commented
@CST1229 If possible, check whether this causes less lag.

2024-07-20 23:25 UTC, WorldLanguages commented
According to #2822: 

> using waitForElement on div.comments, markAsSeen: [true] does not work when new comments are loaded

2024-07-20 23:27 UTC, WorldLanguages requested changes
When loading a new page, the comments at the top no longer have a "Copy Link" button.

2024-09-04 01:42 UTC, WorldLanguages approved these changes

2024-09-04 01:43 UTC, merged