Add more pages to scratchr2
ScratchAddons/ScratchAddons pull request #775
Opened 2020-11-17 22:57 UTC by GrahamSH-LLK

This adds more pages to scratchr2.
Resolves #774 
Adds:   
		
		"https://scratch.mit.edu/login",
        "https://scratch.mit.edu/login_retry",
        "https://scratch.mit.edu/cloudmonitor/*",
        "https://scratch.mit.edu/accounts/login"

2020-11-18 09:01 UTC, mxmou requested changes

2020-11-18 09:01 UTC, mxmou commented on addons/scratchr2/addon.json
> +        "https://scratch.mit.edu/cloudmonitor/*",
It already matches cloudmonitor (on line 27).

2020-11-18 09:01 UTC, mxmou commented on addons/scratchr2/addon.json
> +        "https://scratch.mit.edu/accounts/*"
Same, line 23.

2020-11-18 13:04 UTC, GrahamSH-LLK commented
@WorldLanguages There is some underlying bug/glitch. I added those because they weren't showing up.

2020-11-18 16:10 UTC, WorldLanguages commented
@GrahamSH-LLK Please create a bug report issue with clear reproduction steps

2020-11-18 22:24 UTC, GrahamSH-LLK commented
> Please create a bug report issue with clear reproduction steps

The problem is, there is none. Some page loads just are missing addons.

2020-11-19 13:57 UTC, WorldLanguages commented
@GrahamSH-LLK Only issue I've experienced was page loads sometimes not loading any addon if you reloaded the extension recently. I've never experienced some addons/styles being loaded, while others not

2020-11-19 14:00 UTC, mxmou commented
> There is some underlying bug/glitch. I added those because they weren't showing up.

For me they do show up. And if they don't, why would duplicating the pattern fix the problem?

2020-11-19 14:07 UTC, GrahamSH-LLK commented
> > There is some underlying bug/glitch. I added those because they weren't showing up.
> 
> For me they do show up. And if they don't, why would duplicating the pattern fix the problem?

It's not every time. I didn't realize that they were already there. I just noticed that those pages didn't have it, so I added them.

2020-11-20 17:59 UTC, WorldLanguages commented
Should we merge in the current state?

2020-11-20 18:13 UTC, GrahamSH-LLK commented
> Should we merge in the current state?

Yep!

2020-11-20 18:14 UTC, merged