Fix `hide-backpack` incompatibility with auto-hiding zoom controls in `custom-zoom`
ScratchAddons/ScratchAddons pull request #8041
Opened 2024-12-30 12:51 UTC by just-a-hriday

Resolves #8040

### Changes

Added `z-index: 2` to stylesheet in hide-backpack to fix layering issue.

### Tests

Tested on Chrome 131.0.6778.205.

2024-12-30 14:04 UTC, Samq64 approved these changes
There is another compatibility issue when the hide zoom setting is off where the zoom buttons are not aligned properly until the backpack is clicked but that is not caused by this PR.

![image](https://github.com/user-attachments/assets/1947cabe-1583-43b3-80d8-9bb411ea5a0c)

2024-12-31 02:19 UTC, just-a-hriday commented
> There is another compatibility issue when the hide zoom setting is off where the zoom buttons are not aligned properly until the backpack is clicked but that is not caused by this PR.
> 
> ![image](https://github.com/user-attachments/assets/1947cabe-1583-43b3-80d8-9bb411ea5a0c)
> 

Might it be a good idea to make the backpack button hide with the zoom controls?

2024-12-31 02:34 UTC, Samq64 commented
> Might it be a good idea to make the backpack button hide with the zoom controls?

No? The issue above fixes itself when backpack is opened and doesn't happen again after closing it.

2024-12-31 21:01 UTC, mxmou requested changes

2024-12-31 21:01 UTC, mxmou commented on addons/hide-backpack/button.css
> +  z-index: 2;
```suggestion
  z-index: 2; /* above custom zoom controls */
```

2024-12-31 21:02 UTC, mxmou commented
> Might it be a good idea to make the backpack button hide with the zoom controls?

It intentionally doesn't hide: https://github.com/ScratchAddons/ScratchAddons/pull/7288#issuecomment-2016580298

2024-12-31 21:05 UTC, mxmou commented
> There is another compatibility issue when the hide zoom setting is off where the zoom buttons are not aligned properly until the backpack is clicked but that is not caused by this PR.

Can't repro. Does this happen consistently?

2024-12-31 21:27 UTC, Samq64 commented
> Does this happen consistently?

Not anymore.

2025-01-01 08:06 UTC, mxmou approved these changes

2025-01-01 08:07 UTC, merged